import type { Language } from "@/lib/translations";

// Übersetzungen für die Oberfläche im Mitgliederbereich (Profil, Profilseiten, Chat-Übersicht, Anmeldung).
// Der Schlüssel ist der deutsche Text, wie er im Code steht. Platzhalter wie {name} werden eingesetzt.
// Nicht übersetzt werden: der Chat selbst (Nachrichten, Eisbrecher), das Onboarding-Gespräch, Rechtstexte und der Admin-Bereich.
// Fehlt ein Eintrag, bleibt der deutsche Text stehen.
export type Vars = Record<string, string | number>;

type Entry = { en: string; ta: string };

export const UI: Record<string, Entry> = {};

function fill(text: string, vars?: Vars): string {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}

export function translateUi(de: string, language: Language, vars?: Vars): string {
  if (language === "de") return fill(de, vars);
  const entry = UI[de];
  return fill(entry ? entry[language] : de, vars);
}

/** Beschriftung einer Auswahlliste in der gewählten Sprache (Texte kommen aus lib/onboarding.ts). */
export function register(entries: Record<string, [string, string]>): void {
  for (const k of Object.keys(entries)) UI[k] = { en: entries[k][0], ta: entries[k][1] };
}

// ——— Allgemein ———
register({
  "Abbrechen": ["Cancel", "ரத்து செய்"],
  "Bearbeiten": ["Edit", "திருத்து"],
  "Speichern": ["Save", "சேமி"],
  "Speichere …": ["Saving …", "சேமிக்கிறது …"],
  "Gespeichert.": ["Saved.", "சேமிக்கப்பட்டது."],
  "Weiter": ["Next", "தொடர்"],
  "Löschen": ["Delete", "நீக்கு"],
  "Lösche …": ["Deleting …", "நீக்குகிறது …"],
  "Entfernen": ["Remove", "அகற்று"],
  "Schließen": ["Close", "மூடு"],
  "Hinzufügen": ["Add", "சேர்"],
  "Ja": ["Yes", "ஆம்"],
  "Nein": ["No", "இல்லை"],
  "Prüfen": ["Check", "சரிபார்"],
  "Übernehmen": ["Apply", "ஏற்றுக்கொள்"],
  "bis": ["to", "வரை"],
  "von": ["from", "முதல்"],
  "Anderes": ["Other", "மற்றவை"],
  "Sende …": ["Sending …", "அனுப்புகிறது …"],
  "Keine Verbindung. Bitte versuch es noch einmal.": ["No connection. Please try again.", "இணைப்பு இல்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்."],
  "Speichern hat nicht geklappt.": ["Saving didn't work.", "சேமிக்க முடியவில்லை."],
  "Das hat nicht geklappt.": ["That didn't work.", "அது வெற்றிபெறவில்லை."],
  "Bitte melde dich zuerst an.": ["Please sign in first.", "முதலில் உள்நுழையவும்."],
  "Chat": ["Chat", "அரட்டை"],
  "Zur Startseite": ["Back to the home page", "முகப்புப் பக்கத்திற்கு"],
  "Abmelden": ["Sign out", "வெளியேறு"],
  "Sprache": ["Language", "மொழி"],
});

// ——— Auswahllisten (Texte aus lib/onboarding.ts) ———
register({
  "Friends-Community": ["Friends community", "நட்பு சமூகம்"],
  "Business-Community": ["Business community", "வணிக சமூகம்"],
  "Männlich": ["Male", "ஆண்"],
  "Weiblich": ["Female", "பெண்"],
  "Nicht-binär / divers": ["Non-binary / diverse", "பைனரி அல்லாதவர் / பன்முகம்"],
  "Möchte ich nicht angeben": ["Prefer not to say", "குறிப்பிட விரும்பவில்லை"],
  "Keine Angabe": ["Not specified", "குறிப்பிடப்படவில்லை"],
  "Männliche Freundschaften": ["Male friendships", "ஆண் நட்புகள்"],
  "Weibliche Freundschaften": ["Female friendships", "பெண் நட்புகள்"],
  "Egal, mir ist es wichtig, dass es passt": ["Doesn't matter, what counts is that it fits", "முக்கியமில்லை, பொருத்தம்தான் முக்கியம்"],
  "Gemischte Gruppe": ["Mixed group", "கலப்புக் குழு"],
  "Nur Männer": ["Men only", "ஆண்கள் மட்டும்"],
  "Nur Frauen": ["Women only", "பெண்கள் மட்டும்"],
  "Egal, Hauptsache Match": ["Doesn't matter, as long as it's a match", "முக்கியமில்லை, பொருத்தம் இருந்தால் போதும்"],
  "Duo (2er Gruppe)": ["Duo (group of 2)", "இருவர் (2 பேர் குழு)"],
  "Crew (4er Gruppe)": ["Crew (group of 4)", "குழு (4 பேர்)"],
  "Squad (8er Gruppe)": ["Squad (group of 8)", "பெரிய குழு (8 பேர்)"],
  "Egal": ["Any", "எதுவாயினும்"],
  "Nur online schreiben": ["Online chatting only", "ஆன்லைனில் மட்டும் பேசுதல்"],
  "Auch gemeinsame Aktivitäten und Hobbys vor Ort": ["Also shared activities and hobbies in person", "நேரில் இணைந்து செயல்பாடுகளும் பொழுதுபோக்குகளும்"],
  "10 Minuten": ["10 minutes", "10 நிமிடங்கள்"],
  "20 Minuten": ["20 minutes", "20 நிமிடங்கள்"],
  "45 Minuten": ["45 minutes", "45 நிமிடங்கள்"],
  "1 Stunde": ["1 hour", "1 மணி நேரம்"],
  "2 Stunden": ["2 hours", "2 மணி நேரம்"],
  "Seltener als 1× im Monat": ["Less than once a month", "மாதம் ஒருமுறைக்கும் குறைவாக"],
  "1–2× im Monat": ["1–2 times a month", "மாதம் 1–2 முறை"],
  "1–2× pro Woche": ["1–2 times a week", "வாரம் 1–2 முறை"],
  "3× pro Woche oder öfter": ["3 times a week or more", "வாரம் 3 முறை அல்லது அதற்கு மேல்"],
  "Tamil": ["Tamil", "தமிழ்"],
  "Deutsch": ["German", "ஜெர்மன்"],
  "Englisch": ["English", "ஆங்கிலம்"],
  "Französisch": ["French", "பிரெஞ்சு"],
  "Mix aus allem": ["A mix of everything", "அனைத்தும் கலந்து"],
  "Schule": ["School", "பள்ளி"],
  "Studium": ["University", "கல்லூரிப் படிப்பு"],
  "Ausbildung": ["Apprenticeship", "தொழிற்பயிற்சி"],
  "Beruf": ["Work", "வேலை"],
  "Sonstiges": ["Other", "மற்றவை"],
  "Gym": ["Gym", "உடற்பயிற்சி நிலையம்"],
  "Gaming": ["Gaming", "கேமிங்"],
  "Kultur": ["Culture", "கலாச்சாரம்"],
  "Deep Talks": ["Deep talks", "ஆழமான உரையாடல்கள்"],
  "Musik": ["Music", "இசை"],
  "Tanzen": ["Dancing", "நடனம்"],
  "Essen & Kochen": ["Food & cooking", "உணவு & சமையல்"],
  "Reisen": ["Travel", "பயணம்"],
  "Sport": ["Sports", "விளையாட்டு"],
  "Kreatives": ["Creative things", "படைப்பாற்றல்"],
  "Karriere & Business": ["Career & business", "தொழில் & வணிகம்"],
  "Filme & Serien": ["Movies & series", "திரைப்படங்கள் & தொடர்கள்"],
  "Entspannt": ["Relaxed", "நிதானமானவர்"],
  "Zielorientiert": ["Goal-oriented", "இலக்கை நோக்கியவர்"],
  "Kreativ": ["Creative", "படைப்பாற்றல் மிக்கவர்"],
  "Abenteuerlustig": ["Adventurous", "சாகசப் பிரியர்"],
  "Humorvoll": ["Humorous", "நகைச்சுவை உணர்வுள்ளவர்"],
  "Tiefgründig": ["Thoughtful", "ஆழ்ந்து சிந்திப்பவர்"],
  "Spontan": ["Spontaneous", "தன்னிச்சையானவர்"],
  "Bodenständig": ["Down to earth", "எளிமையானவர்"],
  "Öffentlich": ["Public", "பொது"],
  "Nur Business": ["Business only", "வணிகர்கள் மட்டும்"],
  "Privat": ["Private", "தனிப்பட்டது"],
  "Online": ["Online", "ஆன்லைன்"],
  "Warteliste (noch kein Hub in der Nähe)": ["Waiting list (no hub nearby yet)", "காத்திருப்புப் பட்டியல் (அருகில் இன்னும் மையம் இல்லை)"],
  "Berlin & Ost": ["Berlin & East", "பெர்லின் & கிழக்கு"],
  "Hamburg & Nord": ["Hamburg & North", "ஹாம்பர்க் & வடக்கு"],
  "Bayern": ["Bavaria", "பவேரியா"],
  "Schweiz": ["Switzerland", "சுவிட்சர்லாந்து"],
  "Österreich": ["Austria", "ஆஸ்திரியா"],
  "Tech & Software": ["Tech & software", "தொழில்நுட்பம் & மென்பொருள்"],
  "Finanzen & Investment": ["Finance & investment", "நிதி & முதலீடு"],
  "Gesundheit & Medizin": ["Health & medicine", "சுகாதாரம் & மருத்துவம்"],
  "Handel & E-Commerce": ["Retail & e-commerce", "வர்த்தகம் & இ-காமர்ஸ்"],
  "Medien & Kreatives": ["Media & creative", "ஊடகம் & படைப்பாற்றல்"],
  "Bildung & Forschung": ["Education & research", "கல்வி & ஆராய்ச்சி"],
  "Gastronomie & Food": ["Hospitality & food", "உணவகத் துறை & உணவு"],
  "Immobilien & Bau": ["Real estate & construction", "ரியல் எஸ்டேட் & கட்டுமானம்"],
  "Beratung & Services": ["Consulting & services", "ஆலோசனை & சேவைகள்"],
  "Industrie & Handwerk": ["Industry & crafts", "தொழிற்துறை & கைவினை"],
  "Co-Founder finden": ["Find a co-founder", "இணை நிறுவனரைக் கண்டறிதல்"],
  "Investoren-Austausch": ["Exchange with investors", "முதலீட்டாளர்களுடன் கலந்துரையாடல்"],
  "Projekt-Kollaboration": ["Project collaboration", "திட்டக் கூட்டுப்பணி"],
  "Mentoring": ["Mentoring", "வழிகாட்டுதல்"],
  "Kunden & Partner finden": ["Find customers & partners", "வாடிக்கையாளர்கள் & கூட்டாளிகளைக் கண்டறிதல்"],
  "Netzwerk aufbauen": ["Build a network", "தொடர்பு வலையமைப்பை உருவாக்குதல்"],
});

// ——— Steckbrief-Beschriftungen ———
register({
  "Geschlecht": ["Gender", "பாலினம்"],
  "Verbinden mit": ["Connect with", "இணைக்க விரும்புவது"],
  "Alter": ["Age", "வயது"],
  "Gesuchtes Alter": ["Preferred age", "விரும்பும் வயது"],
  "Gruppengröße": ["Group size", "குழு அளவு"],
  "Art der Freundschaft": ["Type of friendship", "நட்பின் வகை"],
  "Max. Entfernung (Auto)": ["Max. distance (car)", "அதிகபட்ச தூரம் (கார்)"],
  "Sprachen": ["Languages", "மொழிகள்"],
  "Lebensphase": ["Life stage", "வாழ்க்கை நிலை"],
  "Hub": ["Hub", "மையம்"],
  "Hubs": ["Hubs", "மையங்கள்"],
  "Stadt": ["City", "நகரம்"],
  "Interessen": ["Interests", "ஆர்வங்கள்"],
  "Vibe": ["Vibe", "இயல்பு"],
  "Grund für zwei Hubs": ["Reason for two hubs", "இரண்டு மையங்களுக்கான காரணம்"],
  "Maximale Treffhäufigkeit": ["Max. meeting frequency", "அதிகபட்ச சந்திப்பு அடிக்கடி"],
  "Business": ["Business", "வணிகம்"],
  "Business-Ziele": ["Business goals", "வணிக இலக்குகள்"],
  "Expertise": ["Expertise", "நிபுணத்துவம்"],
});

// ——— Profil (Hauptseite) ———
register({
  "DSpora Profil": ["DSpora profile", "DSpora சுயவிவரம்"],
  "Hey {name}": ["Hey {name}", "வணக்கம் {name}"],
  "Willkommen": ["Welcome", "வரவேற்கிறோம்"],
  "Admin Dashboard": ["Admin dashboard", "நிர்வாகப் பலகை"],
  "Deine Matches warten": ["Your matches are waiting", "உங்கள் இணைப்புகள் காத்திருக்கின்றன"],
  "Dein Hub bereitet Matches vor": ["Your hub is preparing matches", "உங்கள் மையம் இணைப்புகளைத் தயார் செய்கிறது"],
  "Wir prüfen die Anmeldungen und öffnen deinen Hub, sobald genug passende Leute dabei sind. Jedes Match schauen wir uns vorher an. Du musst nichts weiter tun.": [
    "We review the sign-ups and open your hub as soon as enough suitable people have joined. We look at every match beforehand. You don't have to do anything else.",
    "பதிவுகளை நாங்கள் பரிசீலித்து, போதுமான பொருத்தமானவர்கள் சேர்ந்தவுடன் உங்கள் மையத்தைத் திறக்கிறோம். ஒவ்வொரு இணைப்பையும் முன்கூட்டியே பார்க்கிறோம். நீங்கள் வேறு எதுவும் செய்ய வேண்டியதில்லை.",
  ],
  "{n} aktiver Chat (höchstens 4)": ["{n} active chat (max. 4)", "{n} செயலில் உள்ள அரட்டை (அதிகபட்சம் 4)"],
  "{n} aktive Chats (höchstens 4)": ["{n} active chats (max. 4)", "{n} செயலில் உள்ள அரட்டைகள் (அதிகபட்சம் 4)"],
  "Dein Hub bereitet passende Verbindungen vor": ["Your hub is preparing suitable connections", "உங்கள் மையம் பொருத்தமான இணைப்புகளைத் தயார் செய்கிறது"],
  "Dein Hub bereitet passende Business-Verbindungen vor": ["Your hub is preparing suitable business connections", "உங்கள் மையம் பொருத்தமான வணிக இணைப்புகளைத் தயார் செய்கிறது"],
  "Pausiert. Wechsle oben auf „Friends-Community“, um sie zu aktivieren.": ["Paused. Switch to “Friends community” above to activate it.", "இடைநிறுத்தப்பட்டது. செயல்படுத்த மேலே “நட்பு சமூகம்” என்பதற்கு மாறவும்."],
  "Nicht aktiv. Wechsle oben auf „Business-Community“, um sie zu aktivieren.": ["Not active. Switch to “Business community” above to activate it.", "செயலில் இல்லை. செயல்படுத்த மேலே “வணிக சமூகம்” என்பதற்கு மாறவும்."],
  "Profil und Antworten sind gespeichert": ["Profile and answers are saved", "சுயவிவரமும் பதில்களும் சேமிக்கப்பட்டன"],
  "{n} Anmeldung im Hub {hub}": ["{n} sign-up in the {hub} hub", "{hub} மையத்தில் {n} பதிவு"],
  "{n} Anmeldungen im Hub {hub}": ["{n} sign-ups in the {hub} hub", "{hub} மையத்தில் {n} பதிவுகள்"],
  "Matching: in Vorbereitung": ["Matching: in preparation", "இணைப்பு: தயாராகிறது"],
  "Dein Profil": ["Your profile", "உங்கள் சுயவிவரம்"],
  "Modus": ["Mode", "முறை"],
  "Für den Business-Modus brauchen wir noch ein paar Angaben und dein Light-CV.": ["For business mode we still need a few details and your light CV.", "வணிக முறைக்கு இன்னும் சில விவரங்களும் உங்கள் சுருக்கமான சுயவிவரமும் தேவை."],
  "Business-Profil einrichten": ["Set up business profile", "வணிகச் சுயவிவரத்தை அமைக்கவும்"],
  "Art der Freundschaft und Wohnort": ["Type of friendship and place of residence", "நட்பின் வகை மற்றும் வசிப்பிடம்"],
  "Ort ändern": ["Change place", "இடத்தை மாற்று"],
  "Dein Wohnort": ["Your place of residence", "உங்கள் வசிப்பிடம்"],
  "Bitte gib deinen Wohnort an.": ["Please enter your place of residence.", "உங்கள் வசிப்பிடத்தை உள்ளிடவும்."],
  "Diesen Ort konnte ich nicht zuordnen. Bitte gib die nächstgrößere Stadt an.": ["I couldn't match this place. Please enter the nearest larger city.", "இந்த இடத்தைப் பொருத்த முடியவில்லை. அருகிலுள்ள பெரிய நகரத்தை உள்ளிடவும்."],
  "„{name}“ gehört zum Hub {hub}.": ["“{name}” belongs to the {hub} hub.", "“{name}” {hub} மையத்தைச் சேர்ந்தது."],
  "Wie weit darf jemand maximal entfernt wohnen? (Fahrzeit mit dem Auto)": ["How far away may someone live at most? (driving time by car)", "ஒருவர் அதிகபட்சம் எவ்வளவு தூரத்தில் வசிக்கலாம்? (காரில் பயண நேரம்)"],
  "Maximale Entfernung": ["Maximum distance", "அதிகபட்ச தூரம்"],
  "Wie oft würdest du dich realistisch treffen?": ["How often would you realistically meet?", "நடைமுறையில் எவ்வளவு அடிக்கடி சந்திப்பீர்கள்?"],
  "Treffhäufigkeit": ["Meeting frequency", "சந்திப்பு அடிக்கடி"],
  "Alter und gesuchte Altersspanne": ["Age and preferred age range", "வயது மற்றும் விரும்பும் வயது வரம்பு"],
  "Dein Alter": ["Your age", "உங்கள் வயது"],
  "Gesucht von": ["Looking for", "தேடும் வயது"],
  "Gesucht ab": ["Looking from age", "இந்த வயதிலிருந்து"],
  "Gesucht bis": ["Looking up to age", "இந்த வயது வரை"],
  "bis": ["to", "–"],
  "Bitte gib Zahlen zwischen {min} und {max} an.": ["Please enter numbers between {min} and {max}.", "{min} மற்றும் {max} இடையே எண்களை உள்ளிடவும்."],
  "Altersspanne: „von“ darf nicht größer sein als „bis“.": ["Age range: “from” must not be greater than “to”.", "வயது வரம்பு: தொடக்க வயது இறுதி வயதை விடப் பெரிதாக இருக்கக் கூடாது."],
  "Eine andere Sprache? Eigene hinzufügen": ["Another language? Add your own", "வேறு மொழியா? உங்களுடையதைச் சேர்க்கவும்"],
  "Es zählt, wie du dich selbst identifizierst.": ["What counts is how you identify yourself.", "நீங்கள் உங்களை எவ்வாறு அடையாளப்படுத்துகிறீர்கள் என்பதே முக்கியம்."],
  "Mit wem möchtest du dich verbinden?": ["Who would you like to connect with?", "யாருடன் இணைய விரும்புகிறீர்கள்?"],
  "Gewünschte Gruppengröße": ["Desired group size", "விரும்பும் குழு அளவு"],
  "Eigenes hinzufügen": ["Add your own", "உங்களுடையதைச் சேர்க்கவும்"],
  "Eigenen Vibe hinzufügen": ["Add your own vibe", "உங்கள் இயல்பைச் சேர்க்கவும்"],
  "Für den Business-Modus brauchst du ein Profil mit Namen. Lege es zuerst an.": ["For business mode you need a profile with a name. Please create it first.", "வணிக முறைக்குப் பெயருடன் சுயவிவரம் தேவை. முதலில் அதை உருவாக்கவும்."],
  "Deine Chats": ["Your chats", "உங்கள் அரட்டைகள்"],
  "Du kannst höchstens vier Chats gleichzeitig führen, damit jedes Gespräch echten Fokus bekommt. Verlässt du einen Chat, wird ein Platz für ein neues Match frei.": [
    "You can have at most four chats at the same time so that every conversation gets real focus. If you leave a chat, a spot opens up for a new match.",
    "ஒவ்வொரு உரையாடலுக்கும் உண்மையான கவனம் கிடைக்க, ஒரே நேரத்தில் அதிகபட்சம் நான்கு அரட்டைகளை மட்டுமே நடத்தலாம். ஒரு அரட்டையை விட்டு வெளியேறினால், புதிய இணைப்புக்கு இடம் கிடைக்கும்.",
  ],
  "{n} von 4": ["{n} of 4", "4 இல் {n}"],
  "Zu den Chats": ["Go to chats", "அரட்டைகளுக்குச் செல்"],
  "{n} neu": ["{n} new", "{n} புதியவை"],
  "Dein Steckbrief": ["Your profile summary", "உங்கள் விவரச்சுருக்கம்"],
  "Das weiß DSpora aktuell über dich. So kann die KI dich immer auf dem neuesten Stand ansprechen. Erzähl ihr jederzeit Neues, oder entferne Angaben, die nicht mehr stimmen. Gefragt wird sie auch im Gespräch („Zeig mir meinen Steckbrief“).": [
    "This is what DSpora currently knows about you. That way the AI can always talk to you with up-to-date information. Tell it something new at any time, or remove details that are no longer true. You can also ask for it in the conversation (“Show me my profile summary”).",
    "DSpora தற்போது உங்களைப் பற்றி அறிந்தவை இவை. இதன் மூலம் AI எப்போதும் சமீபத்திய தகவலுடன் உங்களுடன் பேச முடியும். எப்போது வேண்டுமானாலும் புதியதைச் சொல்லுங்கள், அல்லது இனி சரியில்லாத விவரங்களை அகற்றுங்கள். உரையாடலிலும் இதைக் கேட்கலாம் (“என் விவரச்சுருக்கத்தைக் காட்டு”).",
  ],
  "Das hast du erzählt": ["What you told us", "நீங்கள் கூறியவை"],
  "Noch nichts. Im Gespräch lernt die KI dich besser kennen.": ["Nothing yet. In the conversation the AI gets to know you better.", "இன்னும் எதுவும் இல்லை. உரையாடலில் AI உங்களை நன்றாக அறிந்துகொள்கிறது."],
  "Diese Angabe entfernen": ["Remove this entry", "இந்த விவரத்தை அகற்று"],
  "Mit der KI sprechen": ["Talk to the AI", "AI உடன் பேசுங்கள்"],
  "Deine Ideen für DSpora": ["Your ideas for DSpora", "DSpora க்கான உங்கள் யோசனைகள்"],
  "Was wünschst du dir? Welche Features sollten wir unbedingt einbauen? Wir lesen jede Idee.": ["What do you wish for? Which features should we definitely build? We read every idea.", "நீங்கள் என்ன விரும்புகிறீர்கள்? எந்த அம்சங்களை நாங்கள் கண்டிப்பாகச் சேர்க்க வேண்டும்? ஒவ்வொரு யோசனையையும் படிக்கிறோம்."],
  "Meine Idee …": ["My idea …", "என் யோசனை …"],
  "Idee für DSpora": ["Idea for DSpora", "DSpora க்கான யோசனை"],
  "Idee senden": ["Send idea", "யோசனையை அனுப்பு"],
  "Vorschau: nichts wurde gespeichert.": ["Preview: nothing was saved.", "முன்னோட்டம்: எதுவும் சேமிக்கப்படவில்லை."],
  "Danke! Deine Idee ist angekommen.": ["Thank you! Your idea has arrived.", "நன்றி! உங்கள் யோசனை கிடைத்தது."],
  "Schneller anmelden": ["Sign in faster", "விரைவாக உள்நுழைக"],
  "Mit einem Passkey meldest du dich per Face ID, Touch ID oder Schlüsselbund an. Ein Passwort gibt es bei DSpora nicht.": [
    "With a passkey you sign in using Face ID, Touch ID or your keychain. DSpora has no passwords.",
    "Passkey மூலம் Face ID, Touch ID அல்லது கீசெயின் பயன்படுத்தி உள்நுழைகிறீர்கள். DSpora வில் கடவுச்சொல் இல்லை.",
  ],
  "Passkey hinzufügen": ["Add a passkey", "Passkey சேர்"],
  "Der Passkey konnte nicht angelegt werden.": ["The passkey could not be created.", "Passkey ஐ உருவாக்க முடியவில்லை."],
  "Passkey hinzugefügt. Ab jetzt kannst du dich mit Face ID oder Touch ID anmelden.": ["Passkey added. From now on you can sign in with Face ID or Touch ID.", "Passkey சேர்க்கப்பட்டது. இனி Face ID அல்லது Touch ID மூலம் உள்நுழையலாம்."],
  "Benachrichtigungen": ["Notifications", "அறிவிப்புகள்"],
  "E-Mail, wenn ein neuer Chat auf dich wartet": ["Email when a new chat is waiting for you", "புதிய அரட்டை காத்திருக்கும்போது மின்னஞ்சல்"],
  "Die Mail enthält keine Angaben zu deinem Match, nur einen Link in dein Profil.": ["The email contains no details about your match, only a link to your profile.", "மின்னஞ்சலில் உங்கள் இணைப்பைப் பற்றிய விவரங்கள் இல்லை, உங்கள் சுயவிவரத்திற்கான இணைப்பு மட்டுமே."],
  "Konto löschen": ["Delete account", "கணக்கை நீக்கு"],
  "Dein Konto wird sofort gesperrt. Deine Daten bleiben noch 30 Tage gespeichert, falls du es dir anders überlegst oder Hilfe brauchst. Danach werden sie endgültig gelöscht.": [
    "Your account is blocked immediately. Your data stays stored for 30 more days in case you change your mind or need help. After that it is deleted permanently.",
    "உங்கள் கணக்கு உடனடியாக முடக்கப்படும். நீங்கள் மனம் மாறினால் அல்லது உதவி தேவைப்பட்டால் உங்கள் தரவு 30 நாட்கள் சேமிக்கப்படும். அதன் பிறகு அவை நிரந்தரமாக நீக்கப்படும்.",
  ],
  "Konto löschen …": ["Delete account …", "கணக்கை நீக்கு …"],
  "Möchtest du dein Konto wirklich löschen?": ["Do you really want to delete your account?", "உங்கள் கணக்கை உண்மையிலேயே நீக்க விரும்புகிறீர்களா?"],
  "Ja, Konto löschen": ["Yes, delete account", "ஆம், கணக்கை நீக்கு"],
  "Das Konto konnte nicht gelöscht werden. Bitte versuch es noch einmal.": ["The account could not be deleted. Please try again.", "கணக்கை நீக்க முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்."],
  "Chat erneut durchspielen": ["Go through the chat again", "அரட்டையை மீண்டும் நடத்து"],
});

// ——— Auswahlfelder ———
register({
  "Wähle mindestens eins": ["Choose at least one", "குறைந்தது ஒன்றைத் தேர்ந்தெடுக்கவும்"],
  "Optional": ["Optional", "விருப்பத்திற்குரியது"],
  "{n} gewählt": ["{n} selected", "{n} தேர்ந்தெடுக்கப்பட்டன"],
  "2 bis 30 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["2 to 30 characters, only letters, numbers and simple characters.", "2 முதல் 30 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
});

// ——— Business-Angaben ———
register({
  "Business & Light-CV": ["Business & light CV", "வணிகம் & சுருக்கச் சுயவிவரம்"],
  "Bitte gib deine Rolle an.": ["Please enter your role.", "உங்கள் பங்கை உள்ளிடவும்."],
  "Bitte wähle eine Branche.": ["Please choose an industry.", "ஒரு துறையைத் தேர்ந்தெடுக்கவும்."],
  "Bitte wähle mindestens ein Ziel.": ["Please choose at least one goal.", "குறைந்தது ஒரு இலக்கைத் தேர்ந்தெடுக்கவும்."],
  "Branche / Sektor": ["Industry / sector", "துறை / பிரிவு"],
  "Andere Branche? Eigene Angabe": ["Another industry? Enter your own", "வேறு துறையா? உங்களுடையதை உள்ளிடவும்"],
  "Aktuelle Rolle": ["Current role", "தற்போதைய பங்கு"],
  "z. B. Gründerin, Product Manager": ["e.g. founder, product manager", "எ.கா. நிறுவனர், தயாரிப்பு மேலாளர்"],
  "Hauptziel": ["Main goal", "முக்கிய இலக்கு"],
  "bis zu 3": ["up to 3", "3 வரை"],
  "Ein anderes Ziel?": ["Another goal?", "வேறு இலக்கா?"],
  "Branche:": ["Industry:", "துறை:"],
  "· Rolle:": ["· Role:", "· பங்கு:"],
  "Expertise:": ["Expertise:", "நிபுணத்துவம்:"],
  "Expertise": ["Expertise", "நிபுணத்துவம்"],
  "Worin bist du richtig gut? z. B. Produktstrategie, Fullstack, Vertrieb": ["What are you really good at? e.g. product strategy, full-stack, sales", "நீங்கள் எதில் மிகவும் திறமையானவர்? எ.கா. தயாரிப்பு உத்தி, ஃபுல்ஸ்டாக், விற்பனை"],
  "Deine Top-3-Erfolge": ["Your top 3 achievements", "உங்கள் முதல் 3 சாதனைகள்"],
  "kurz, optional": ["short, optional", "சுருக்கமாக, விருப்பத்திற்குரியது"],
  "Links": ["Links", "இணைப்புகள்"],
  "Portfolio, GitHub, Website, optional": ["Portfolio, GitHub, website, optional", "போர்ட்ஃபோலியோ, GitHub, வலைத்தளம், விருப்பத்திற்குரியது"],
});

// ——— Anmeldung ———
register({
  "Willkommen zurück": ["Welcome back", "மீண்டும் வருக"],
  "Ohne Passwort: Wir schicken dir einen Link oder du nutzt deinen Passkey.": ["No password: we send you a link, or you use your passkey.", "கடவுச்சொல் இல்லை: நாங்கள் இணைப்பை அனுப்புகிறோம் அல்லது உங்கள் Passkey ஐப் பயன்படுத்தலாம்."],
  "Die Anmeldung wird gerade eingerichtet und ist bald verfügbar.": ["Sign-in is being set up and will be available soon.", "உள்நுழைவு அமைக்கப்படுகிறது, விரைவில் கிடைக்கும்."],
  "Check dein Postfach: Wir haben dir einen Link an {email} geschickt.": ["Check your inbox: we sent a link to {email}.", "உங்கள் இன்பாக்ஸைப் பாருங்கள்: {email} முகவரிக்கு இணைப்பை அனுப்பியுள்ளோம்."],
  "Schau auch im Spam-Ordner nach.": ["Also check your spam folder.", "ஸ்பேம் கோப்புறையையும் பாருங்கள்."],
  "E-Mail-Adresse": ["Email address", "மின்னஞ்சல் முகவரி"],
  "oder": ["or", "அல்லது"],
  "deine@mail.com": ["your@mail.com", "உங்கள்@mail.com"],
  "Bitte gib eine gültige E-Mail-Adresse ein.": ["Please enter a valid email address.", "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்."],
  "Das hat leider nicht geklappt. Bitte versuch es noch einmal.": ["Unfortunately that didn't work. Please try again.", "துரதிர்ஷ்டவசமாக அது வெற்றிபெறவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்."],
  "Mit dem Passkey hat es nicht geklappt. Du kannst dir stattdessen einen Link per E-Mail schicken lassen.": ["The passkey didn't work. You can have a link sent by email instead.", "Passkey வேலை செய்யவில்லை. அதற்குப் பதிலாக மின்னஞ்சலில் இணைப்பைப் பெறலாம்."],
  "Erneut senden in {n} s": ["Send again in {n} s", "{n} வினாடியில் மீண்டும் அனுப்பலாம்"],
  "Link erneut senden": ["Send link again", "இணைப்பை மீண்டும் அனுப்பு"],
  "Link per E-Mail senden": ["Send link by email", "இணைப்பை மின்னஞ்சலில் அனுப்பு"],
  "Warte auf dein Gerät …": ["Waiting for your device …", "உங்கள் சாதனத்திற்காகக் காத்திருக்கிறது …"],
  "Mit Passkey anmelden": ["Sign in with passkey", "Passkey மூலம் உள்நுழை"],
});

// ——— Chat-Übersicht und Chat-Fenster (ohne die Nachrichten selbst) ———
register({
  "← Profil": ["← Profile", "← சுயவிவரம்"],
  "← Chats": ["← Chats", "← அரட்டைகள்"],
  "Du kannst höchstens vier Chats gleichzeitig führen": ["You can have at most four chats at the same time", "ஒரே நேரத்தில் அதிகபட்சம் நான்கு அரட்டைகள் மட்டுமே"],
  "{n} von {max} Plätzen belegt": ["{n} of {max} spots taken", "{max} இடங்களில் {n} நிரம்பியுள்ளன"],
  "Du kannst höchstens {max} Chats gleichzeitig führen, damit jedes Gespräch Raum bekommt. Verlässt du einen Chat, wird ein Platz für ein neues Match frei.": [
    "You can have at most {max} chats at the same time so that every conversation gets room. If you leave a chat, a spot opens up for a new match.",
    "ஒவ்வொரு உரையாடலுக்கும் இடம் கிடைக்க, ஒரே நேரத்தில் அதிகபட்சம் {max} அரட்டைகளை மட்டுமே நடத்தலாம். ஒரு அரட்டையை விட்டு வெளியேறினால், புதிய இணைப்புக்கு இடம் கிடைக்கும்.",
  ],
  "Noch keine Chats": ["No chats yet", "இன்னும் அரட்டைகள் இல்லை"],
  "Sobald dein Hub öffnet und wir passende Menschen für dich gefunden haben, startet hier dein erster Chat, mit einem Eisbrecher, der zu euren Gemeinsamkeiten passt.": [
    "As soon as your hub opens and we have found suitable people for you, your first chat starts here, with an icebreaker that fits what you have in common.",
    "உங்கள் மையம் திறந்து, உங்களுக்குப் பொருத்தமானவர்களைக் கண்டறிந்தவுடன், உங்கள் பொதுவான விஷயங்களுக்குப் பொருந்தும் ஒரு தொடக்கக் கேள்வியுடன் உங்கள் முதல் அரட்டை இங்கே தொடங்கும்.",
  ],
  "Die Chats konnten nicht geladen werden.": ["The chats could not be loaded.", "அரட்டைகளை ஏற்ற முடியவில்லை."],
  "Allein im Chat": ["Alone in the chat", "அரட்டையில் தனியாக"],
  "Duo": ["Duo", "இருவர்"],
  "Gruppe · {n} Personen": ["Group · {n} people", "குழு · {n} பேர்"],
  " · Business": [" · Business", " · வணிகம்"],
  " · beendet": [" · ended", " · முடிந்தது"],
  "Chat wird geladen …": ["Loading chat …", "அரட்டை ஏற்றப்படுகிறது …"],
  "Melden": ["Report", "புகாரளி"],
  "Profil ansehen": ["View profile", "சுயவிவரத்தைப் பார்"],
  "Chat entfernen": ["Remove chat", "அரட்டையை அகற்று"],
  "Verlassen": ["Leave", "வெளியேறு"],
  "Chat endgültig entfernen?": ["Remove chat permanently?", "அரட்டையை நிரந்தரமாக அகற்றவா?"],
  "Wirklich verlassen? Der Platz wird frei.": ["Really leave? Your spot will be freed.", "உண்மையிலேயே வெளியேறவா? உங்கள் இடம் விடுவிக்கப்படும்."],
  "Was ist passiert?": ["What happened?", "என்ன நடந்தது?"],
  "Wir lesen keine Nachrichten mit, ein kurzer Hinweis hilft uns. Du verlässt danach den Chat und wirst mit dieser Person nicht noch einmal zusammengebracht.": [
    "We don't read any messages; a short note helps us. You will then leave the chat and will not be matched with this person again.",
    "நாங்கள் செய்திகளைப் படிப்பதில்லை; ஒரு சிறு குறிப்பு எங்களுக்கு உதவும். அதன் பிறகு நீங்கள் அரட்டையை விட்டு வெளியேறுவீர்கள், இந்த நபருடன் மீண்டும் இணைக்கப்பட மாட்டீர்கள்.",
  ],
  "Unangenehm oder respektlos": ["Unpleasant or disrespectful", "அசௌகரியமான அல்லது மரியாதையற்ற"],
  "Belästigung": ["Harassment", "தொல்லை"],
  "Spam oder Werbung": ["Spam or advertising", "ஸ்பேம் அல்லது விளம்பரம்"],
  "Fake-Profil": ["Fake profile", "போலி சுயவிவரம்"],
  "Etwas anderes": ["Something else", "வேறு ஏதாவது"],
  "Kurzer Hinweis (optional)": ["Short note (optional)", "சிறு குறிப்பு (விருப்பத்திற்குரியது)"],
  "Kurzer Hinweis zur Meldung": ["Short note about the report", "புகார் பற்றிய சிறு குறிப்பு"],
  "Melden und Chat verlassen": ["Report and leave chat", "புகாரளித்து அரட்டையை விட்டு வெளியேறு"],
  "Warum ihr gematcht wurdet": ["Why you were matched", "நீங்கள் ஏன் இணைக்கப்பட்டீர்கள்"],
  "Match-Steckbrief": ["Match summary", "இணைப்பு விவரச்சுருக்கம்"],
  "Dieser Steckbrief wird gelöscht, sobald der Chat endet.": ["This summary is deleted as soon as the chat ends.", "அரட்டை முடிந்தவுடன் இந்த விவரச்சுருக்கம் நீக்கப்படும்."],
  "Wie fühlt sich dieser Chat an?": ["How does this chat feel?", "இந்த அரட்டை எப்படி உணர்கிறது?"],
  "Gut": ["Good", "நன்று"],
  "Geht so": ["So-so", "பரவாயில்லை"],
  "Nicht gut": ["Not good", "நன்றாக இல்லை"],
  "Dieser Chat ist beendet. Du kannst ihn oben entfernen, dann ist er endgültig gelöscht.": ["This chat has ended. You can remove it above, then it is deleted permanently.", "இந்த அரட்டை முடிந்துவிட்டது. மேலே அதை அகற்றலாம், பிறகு அது நிரந்தரமாக நீக்கப்படும்."],
  "Spark denkt nach …": ["Spark is thinking …", "Spark சிந்திக்கிறது …"],
  "Eisbrecher": ["Icebreaker", "தொடக்கக் கேள்வி"],
  "Schreib eine Nachricht …": ["Write a message …", "ஒரு செய்தியை எழுதுங்கள் …"],
  "Nachricht": ["Message", "செய்தி"],
  "Senden": ["Send", "அனுப்பு"],
  "Senden hat nicht geklappt.": ["Sending didn't work.", "அனுப்ப முடியவில்லை."],
  "Der Impuls konnte nicht geholt werden.": ["The icebreaker could not be fetched.", "தொடக்கக் கேள்வியைப் பெற முடியவில்லை."],
  "Verlassen hat nicht geklappt.": ["Leaving didn't work.", "வெளியேற முடியவில்லை."],
  "Die Meldung hat nicht geklappt.": ["The report didn't work.", "புகார் அளிக்க முடியவில்லை."],
});

// ——— Profilseite ———
register({
  "Deine Profilseite": ["Your profile page", "உங்கள் சுயவிவரப் பக்கம்"],
  "So sehen dich andere. Beiträge zeigst du mit Bildern, die du wischen kannst.": ["This is how others see you. You show posts with images that can be swiped.", "மற்றவர்கள் உங்களை இப்படிப் பார்க்கிறார்கள். வருடிப் பார்க்கக்கூடிய படங்களுடன் பதிவுகளைக் காட்டுகிறீர்கள்."],
  "Ansehen": ["View", "பார்"],
  "Sichtbarkeit der Profilseite": ["Visibility of the profile page", "சுயவிவரப் பக்கத்தின் தெரிவுநிலை"],
  "Alle angemeldeten Mitglieder sehen Name, Alter, Text, Hobbys und Beiträge.": ["All signed-in members see name, age, text, hobbies and posts.", "உள்நுழைந்த அனைத்து உறுப்பினர்களும் பெயர், வயது, உரை, பொழுதுபோக்குகள் மற்றும் பதிவுகளைப் பார்க்கலாம்."],
  "Business-Mitglieder sehen alles, alle anderen nur Profilbild und Spitzname.": ["Business members see everything, everyone else only the profile picture and nickname.", "வணிக உறுப்பினர்கள் அனைத்தையும் பார்ப்பார்கள், மற்றவர்கள் சுயவிவரப் படம் மற்றும் புனைப்பெயரை மட்டும் பார்ப்பார்கள்."],
  "Nur Profilbild und Spitzname sind sichtbar, und nur für Leute, mit denen du in einem Chat bist.": ["Only the profile picture and nickname are visible, and only to people you are in a chat with.", "சுயவிவரப் படமும் புனைப்பெயரும் மட்டுமே தெரியும், நீங்கள் அரட்டையில் இருப்பவர்களுக்கு மட்டுமே."],
  "Dein Profilbild": ["Your profile picture", "உங்கள் சுயவிவரப் படம்"],
  "Profilbild auswählen": ["Choose profile picture", "சுயவிவரப் படத்தைத் தேர்ந்தெடு"],
  "Lade hoch …": ["Uploading …", "பதிவேற்றுகிறது …"],
  "Bild ändern": ["Change picture", "படத்தை மாற்று"],
  "Profilbild hinzufügen": ["Add profile picture", "சுயவிவரப் படத்தைச் சேர்"],
  "Spitzname oder Künstlername": ["Nickname or stage name", "புனைப்பெயர் அல்லது கலைப்பெயர்"],
  "Vorname (optional)": ["First name (optional)", "முதல் பெயர் (விருப்பத்திற்குரியது)"],
  "Nachname (optional)": ["Last name (optional)", "குடும்பப் பெயர் (விருப்பத்திற்குரியது)"],
  "Name und Nachname siehst nur du, solange dein Profil privat ist.": ["Only you can see first and last name as long as your profile is private.", "உங்கள் சுயவிவரம் தனிப்பட்டதாக இருக்கும் வரை பெயரையும் குடும்பப் பெயரையும் நீங்கள் மட்டுமே பார்க்கலாம்."],
  "Über mich": ["About me", "என்னைப் பற்றி"],
  "Ein paar Sätze über dich …": ["A few sentences about you …", "உங்களைப் பற்றி சில வாக்கியங்கள் …"],
  "Hobbys": ["Hobbies", "பொழுதுபோக்குகள்"],
  "Hobby eintippen, Enter": ["Type a hobby, Enter", "பொழுதுபோக்கை உள்ளிடவும், Enter"],
  "Hobby hinzufügen": ["Add hobby", "பொழுதுபோக்கைச் சேர்"],
  "Beiträge": ["Posts", "பதிவுகள்"],
  "{n} von {max}": ["{n} of {max}", "{max} இல் {n}"],
  "Beitrag löschen": ["Delete post", "பதிவை நீக்கு"],
  "Neuer Beitrag (bis zu {max} Bilder zum Wischen)": ["New post (up to {max} swipeable images)", "புதிய பதிவு (வருடிப் பார்க்க {max} படங்கள் வரை)"],
  "Bilder für den Beitrag auswählen": ["Choose images for the post", "பதிவுக்கான படங்களைத் தேர்ந்தெடு"],
  "Bilder auswählen": ["Choose images", "படங்களைத் தேர்ந்தெடு"],
  "Weitere Bilder": ["More images", "மேலும் படங்கள்"],
  "Bildunterschrift (optional)": ["Caption (optional)", "படத்தலைப்பு (விருப்பத்திற்குரியது)"],
  "Bildunterschrift": ["Caption", "படத்தலைப்பு"],
  "Veröffentliche …": ["Publishing …", "வெளியிடுகிறது …"],
  "Beitrag veröffentlichen": ["Publish post", "பதிவை வெளியிடு"],
  "Höchstens {n} Bilder pro Beitrag.": ["At most {n} images per post.", "ஒரு பதிவுக்கு அதிகபட்சம் {n} படங்கள்."],
  "Höchstens {n} Hobbys.": ["At most {n} hobbies.", "அதிகபட்சம் {n} பொழுதுபோக்குகள்."],
  "Spitzname: 2 bis 24 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["Nickname: 2 to 24 characters, only letters, numbers and simple characters.", "புனைப்பெயர்: 2 முதல் 24 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
  "Hobby: 2 bis 30 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["Hobby: 2 to 30 characters, only letters, numbers and simple characters.", "பொழுதுபோக்கு: 2 முதல் 30 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
  "Das Profilbild konnte nicht hochgeladen werden.": ["The profile picture could not be uploaded.", "சுயவிவரப் படத்தைப் பதிவேற்ற முடியவில்லை."],
  "Der Beitrag konnte nicht veröffentlicht werden.": ["The post could not be published.", "பதிவை வெளியிட முடியவில்லை."],
  "Der Beitrag konnte nicht gelöscht werden.": ["The post could not be deleted.", "பதிவை நீக்க முடியவில்லை."],
  "Dieses Profil ist privat. Mehr als Profilbild und Spitzname siehst du nicht.": ["This profile is private. You only see the profile picture and nickname.", "இந்த சுயவிவரம் தனிப்பட்டது. சுயவிவரப் படமும் புனைப்பெயரும் மட்டுமே தெரியும்."],
  "Noch keine Beiträge.": ["No posts yet.", "இன்னும் பதிவுகள் இல்லை."],
  "Profil bearbeiten": ["Edit profile", "சுயவிவரத்தைத் திருத்து"],
  "{n} Jahre": ["{n} years old", "{n} வயது"],
  "Vorheriges Bild": ["Previous image", "முந்தைய படம்"],
  "Nächstes Bild": ["Next image", "அடுத்த படம்"],
  "Dieses Profil ist privat.": ["This profile is private.", "இந்த சுயவிவரம் தனிப்பட்டது."],
});

register({
  "Profilbild von {name}": ["Profile picture of {name}", "{name} இன் சுயவிவரப் படம்"],
  "Beitrag öffnen": ["Open post", "பதிவைத் திற"],
  "Beitrag von {name}": ["Post by {name}", "{name} இன் பதிவு"],
  "Bild {i} von {n}": ["Image {i} of {n}", "படம் {i} / {n}"],
  "Bild {i}": ["Image {i}", "படம் {i}"],
  "Bild {i} entfernen": ["Remove image {i}", "படம் {i} ஐ அகற்று"],
});

register({
  "Du bist startklar!": ["You're all set!", "நீங்கள் தயார்!"],
  "Anmelden": ["Sign in", "உள்நுழை"],
  "Zum Profil": ["Go to profile", "சுயவிவரத்திற்குச் செல்"],
  "Webseite besuchen": ["Visit website", "இணையதளத்தைப் பார்வையிடு"],
  "Link nicht angekommen? Erneut senden oder andere Adresse": ["Link didn't arrive? Send again or use another address", "இணைப்பு வரவில்லையா? மீண்டும் அனுப்பு அல்லது வேறு முகவரி"],
  "← Zurück zur Startseite": ["← Back to the home page", "← முகப்புப் பக்கத்திற்குத் திரும்பு"],
  "Wir haben dir einen Link an {email} geschickt. Mit einem Klick darauf wirst du angemeldet und dein Profil wird gespeichert.": ["We sent a link to {email}. One click on it signs you in and saves your profile.", "{email} முகவரிக்கு இணைப்பை அனுப்பியுள்ளோம். அதில் ஒரு கிளிக் செய்தால் நீங்கள் உள்நுழைவீர்கள், உங்கள் சுயவிவரம் சேமிக்கப்படும்."],
  "deine E-Mail-Adresse": ["your email address", "உங்கள் மின்னஞ்சல் முகவரி"],
  "Danke, dass du dich weiter geöffnet hast. Deine Antworten sind gespeichert und helfen uns, dich besser kennenzulernen.": ["Thank you for opening up further. Your answers are saved and help us get to know you better.", "மேலும் மனம் திறந்ததற்கு நன்றி. உங்கள் பதில்கள் சேமிக்கப்பட்டுள்ளன, உங்களை நன்றாக அறிய உதவுகின்றன."],
  "Dein Profil ist angelegt. Sobald sich in deinen Hubs genug Leute eintragen, öffnet sich dein Hub und wir melden uns bei dir.": ["Your profile is created. As soon as enough people sign up in your hubs, your hub opens and we will get in touch.", "உங்கள் சுயவிவரம் உருவாக்கப்பட்டது. உங்கள் மையங்களில் போதுமான பேர் பதிவு செய்தவுடன், உங்கள் மையம் திறக்கும், நாங்கள் உங்களைத் தொடர்பு கொள்வோம்."],
  "Dieser Link ist abgelaufen oder wurde schon benutzt. Fordere unten einen neuen an.": ["This link has expired or has already been used. Request a new one below.", "இந்த இணைப்பு காலாவதியாகிவிட்டது அல்லது ஏற்கனவே பயன்படுத்தப்பட்டுவிட்டது. கீழே புதிய இணைப்பைக் கோருங்கள்."],
});

// ——— Onboarding-Gespräch: Phase 1 (Basisfragen) ———
register({
  "Danke dir!": ["Thank you!", "நன்றி!"],
  "Das hilft mir sehr.": ["That helps me a lot.", "இது எனக்கு மிகவும் உதவுகிறது."],
  "Gut zu wissen.": ["Good to know.", "தெரிந்துகொண்டது நல்லது."],
  "Schön, das zu hören.": ["Nice to hear that.", "கேட்க மகிழ்ச்சி."],
  "Verstehe, danke dir.": ["I see, thank you.", "புரிகிறது, நன்றி."],
  "Schön, dass du wieder da bist! Was gibt es Neues bei dir? Erzähl mir gern, was sich geändert hat, oder frag mich nach deinem Steckbrief. Wenn du magst, stelle ich dir auch einfach weitere Fragen.": [
    "Nice to have you back! What's new with you? Feel free to tell me what has changed, or ask me about your profile summary. If you like, I can also simply ask you more questions.",
    "மீண்டும் வந்ததில் மகிழ்ச்சி! உங்களுக்குப் புதிதாக என்ன? என்ன மாறியது என்று சொல்லுங்கள், அல்லது உங்கள் விவரச்சுருக்கத்தைப் பற்றிக் கேளுங்கள். விரும்பினால் நானே மேலும் கேள்விகள் கேட்கிறேன்.",
  ],
  "Willkommen bei DSpora. Lass uns herausfinden, wer wirklich zu dir passt, in deinem Tempo.": ["Welcome to DSpora. Let's find out who really fits you, at your own pace.", "DSpora விற்கு வரவேற்கிறோம். உங்களுக்கு உண்மையில் யார் பொருத்தமானவர் என்பதை உங்கள் வேகத்தில் கண்டறிவோம்."],
  "Phase 1 sind ein paar kurze Fragen (etwa 2 Minuten), die alle beantwortet werden müssen, damit wir passende Leute für dich finden. Danach kannst du freiwillig mit mir weiterreden.": [
    "Phase 1 is a few short questions (about 2 minutes) that all need to be answered so that we can find suitable people for you. Afterwards you can voluntarily keep talking with me.",
    "கட்டம் 1 என்பது சில குறுகிய கேள்விகள் (சுமார் 2 நிமிடங்கள்). உங்களுக்குப் பொருத்தமானவர்களைக் கண்டறிய அனைத்துக்கும் பதிலளிக்க வேண்டும். அதன் பிறகு விரும்பினால் என்னுடன் தொடர்ந்து பேசலாம்.",
  ],
  "Los geht's: Wonach suchst du bei DSpora?": ["Let's go: what are you looking for at DSpora?", "தொடங்குவோம்: DSpora வில் நீங்கள் எதைத் தேடுகிறீர்கள்?"],
  "Perfekt! In welcher Gruppengröße möchtest du Leute treffen?": ["Perfect! In which group size would you like to meet people?", "சரி! எந்த அளவுக் குழுவில் மக்களைச் சந்திக்க விரும்புகிறீர்கள்?"],
  "Danke dir! Als was identifizierst du dich? Du kannst auch etwas Eigenes schreiben.": ["Thank you! How do you identify? You can also write something of your own.", "நன்றி! நீங்கள் உங்களை எப்படி அடையாளப்படுத்துகிறீர்கள்? உங்கள் சொந்தமாகவும் எழுதலாம்."],
  "Gut zu wissen! Welche Freundschaften suchst du?": ["Good to know! What kind of friendships are you looking for?", "தெரிந்துகொண்டது நல்லது! எப்படிப்பட்ட நட்புகளைத் தேடுகிறீர்கள்?"],
  "Gut zu wissen! Welche Gruppe suchst du? Beantworte es so, wie es für dich passt.": ["Good to know! What kind of group are you looking for? Answer however fits you.", "தெரிந்துகொண்டது நல்லது! எப்படிப்பட்ட குழுவைத் தேடுகிறீர்கள்? உங்களுக்குப் பொருந்துவது போல் பதிலளியுங்கள்."],
  "Wie alt bist du?": ["How old are you?", "உங்கள் வயது என்ன?"],
  "Und welche Altersspanne passt dir bei den anderen? Du kannst die Zahlen anpassen.": ["And which age range suits you for the others? You can adjust the numbers.", "மற்றவர்களுக்கு எந்த வயது வரம்பு உங்களுக்குப் பொருந்தும்? எண்களை மாற்றலாம்."],
  "{min} bis {max} Jahre": ["{min} to {max} years", "{min} முதல் {max} வயது வரை"],
  "Wie soll die Freundschaft aussehen?": ["What should the friendship look like?", "நட்பு எப்படி இருக்க வேண்டும்?"],
  "In welcher Stadt wohnst du? Ich ordne dich dann dem nächsten Hub zu.": ["Which city do you live in? I will then assign you to the nearest hub.", "நீங்கள் எந்த நகரத்தில் வசிக்கிறீர்கள்? பின்னர் உங்களை அருகிலுள்ள மையத்துடன் இணைப்பேன்."],
  "Diesen Ort konnte ich leider nicht zuordnen. Bitte gib die nächstgrößere Stadt in deiner Nähe ein.": ["Unfortunately I couldn't match this place. Please enter the nearest larger city near you.", "இந்த இடத்தைப் பொருத்த முடியவில்லை. உங்கள் அருகிலுள்ள பெரிய நகரத்தை உள்ளிடவும்."],
  "Ich habe „{name}“ gefunden. In deiner Nähe gibt es noch keinen Hub. Du kommst auf die Warteliste, und wir melden uns, sobald es einen gibt. Passt das so?": ["I found “{name}”. There is no hub near you yet. You will be put on the waiting list, and we will get in touch as soon as there is one. Is that okay?", "“{name}” ஐக் கண்டறிந்தேன். உங்கள் அருகில் இன்னும் மையம் இல்லை. நீங்கள் காத்திருப்புப் பட்டியலில் சேர்க்கப்படுவீர்கள், மையம் வந்தவுடன் தொடர்பு கொள்வோம். இது சரியா?"],
  "Ich habe „{name}“ gefunden und ordne dich dem Hub {hub} zu. Passt das?": ["I found “{name}” and am assigning you to the {hub} hub. Is that okay?", "“{name}” ஐக் கண்டறிந்து உங்களை {hub} மையத்துடன் இணைக்கிறேன். இது சரியா?"],
  "Anderen Ort eingeben": ["Enter a different place", "வேறு இடத்தை உள்ளிடு"],
  "Kein Problem. Welcher Ort passt besser?": ["No problem. Which place fits better?", "பரவாயில்லை. எந்த இடம் பொருத்தமாக இருக்கும்?"],
  "Ja, passt": ["Yes, that's right", "ஆம், சரி"],
  "Wie weit darf jemand maximal von dir entfernt wohnen? Gemeint ist die Fahrzeit mit dem Auto.": ["How far away may someone live from you at most? This means the driving time by car.", "உங்களிடமிருந்து ஒருவர் அதிகபட்சம் எவ்வளவு தூரத்தில் வசிக்கலாம்? இது காரில் பயண நேரத்தைக் குறிக்கிறது."],
  "Wie oft würdest du dich realistisch mit jemandem treffen?": ["How often would you realistically meet someone?", "நடைமுறையில் ஒருவரை எவ்வளவு அடிக்கடி சந்திப்பீர்கள்?"],
  "Welche Sprachen sprichst du gern mit Freunden? Du kannst mehrere wählen oder eigene eintragen.": ["Which languages do you like to speak with friends? You can choose several or enter your own.", "நண்பர்களுடன் எந்த மொழிகளில் பேச விரும்புகிறீர்கள்? பலவற்றைத் தேர்ந்தெடுக்கலாம் அல்லது உங்களுடையதை உள்ளிடலாம்."],
  "Spannend! In welcher Branche oder welchem Sektor bist du unterwegs?": ["Exciting! Which industry or sector are you in?", "சுவாரஸ்யம்! நீங்கள் எந்தத் துறையில் இருக்கிறீர்கள்?"],
  "Wo stehst du gerade im Leben?": ["Where are you in life right now?", "வாழ்க்கையில் இப்போது எந்த நிலையில் இருக்கிறீர்கள்?"],
  "Und was ist deine aktuelle berufliche Rolle?": ["And what is your current professional role?", "உங்கள் தற்போதைய தொழில்முறைப் பங்கு என்ன?"],
  "Bitte gib deine Rolle an (mindestens 2 Zeichen).": ["Please enter your role (at least 2 characters).", "உங்கள் பங்கை உள்ளிடவும் (குறைந்தது 2 எழுத்துகள்)."],
  "Was ist dein Hauptziel bei DSpora? Wähle bis zu drei oder schreib dein eigenes.": ["What is your main goal at DSpora? Choose up to three or write your own.", "DSpora வில் உங்கள் முக்கிய இலக்கு என்ன? மூன்று வரை தேர்ந்தெடுங்கள் அல்லது உங்களுடையதை எழுதுங்கள்."],
  "Was begeistert dich abseits der Arbeit? Gemeinsame Aktivitäten wie Tennis oder Padel verbinden oft am meisten. Tippe einen Vorschlag an oder schreib eigene Wörter.": ["What excites you outside of work? Shared activities like tennis or padel often connect people the most. Tap a suggestion or write your own words.", "வேலைக்கு அப்பால் உங்களை எது ஈர்க்கிறது? டென்னிஸ் அல்லது பேடல் போன்ற பகிர்ந்த செயல்பாடுகள் பெரும்பாலும் மக்களை அதிகம் இணைக்கும். ஒரு பரிந்துரையைத் தட்டுங்கள் அல்லது உங்கள் சொற்களை எழுதுங்கள்."],
  "Was begeistert dich? Tippe einen Vorschlag an oder schreib eigene Wörter in die Felder.": ["What excites you? Tap a suggestion or write your own words in the fields.", "உங்களை எது ஈர்க்கிறது? ஒரு பரிந்துரையைத் தட்டுங்கள் அல்லது புலங்களில் உங்கள் சொற்களை எழுதுங்கள்."],
  "Und welcher Vibe beschreibt dich am besten? Auch hier gern eigene Wörter.": ["And which vibe describes you best? Feel free to use your own words here too.", "உங்களை எந்த இயல்பு சிறப்பாக விவரிக்கிறது? இங்கும் உங்கள் சொந்தச் சொற்களை எழுதலாம்."],
  "Fast geschafft! Wie sollen wir dich nennen? Ein Spitzname oder Künstlername reicht, so kannst du anonym bleiben. Deinen echten Namen kannst du später im Profil ergänzen.": ["Almost done! What should we call you? A nickname or stage name is enough, so you can stay anonymous. You can add your real name later in your profile.", "கிட்டத்தட்ட முடிந்தது! உங்களை எப்படி அழைக்க வேண்டும்? புனைப்பெயர் அல்லது கலைப்பெயர் போதும், இதனால் அடையாளமின்றி இருக்கலாம். உங்கள் உண்மையான பெயரை பின்னர் சுயவிவரத்தில் சேர்க்கலாம்."],
  "Das war Phase 1, danke dir! Möchtest du mir in Phase 2 noch mehr von dir erzählen? Das ist freiwillig. Ich stelle dir dann passende, tiefere Fragen, damit die Matches noch besser passen.": ["That was phase 1, thank you! Would you like to tell me more about yourself in phase 2? That is voluntary. I will then ask you suitable, deeper questions so that the matches fit even better.", "கட்டம் 1 முடிந்தது, நன்றி! கட்டம் 2 இல் உங்களைப் பற்றி மேலும் சொல்ல விரும்புகிறீர்களா? இது விருப்பத்திற்குரியது. இணைப்புகள் இன்னும் நன்றாகப் பொருந்த, பொருத்தமான ஆழமான கேள்விகளை நான் கேட்பேன்."],
  "Nein, weiter": ["No, continue", "இல்லை, தொடர்"],
  "Ja, gern": ["Yes, gladly", "ஆம், மகிழ்ச்சியுடன்"],
  "Schön! Erzähl frei heraus, was dir wichtig ist, wer du bist oder wonach du suchst. Auch was du nicht magst, hilft mir. Wir können so lange reden, wie du magst, und wenn du Fragen zu DSpora hast, stell sie mir gern zwischendurch.": ["Great! Tell me freely what matters to you, who you are or what you are looking for. What you don't like helps me too. We can talk as long as you like, and if you have questions about DSpora, feel free to ask me in between.", "நல்லது! உங்களுக்கு முக்கியமானது என்ன, நீங்கள் யார், எதைத் தேடுகிறீர்கள் என்பதை மனம்திறந்து சொல்லுங்கள். நீங்கள் விரும்பாதவையும் எனக்கு உதவும். நீங்கள் விரும்பும் வரை பேசலாம், DSpora பற்றிய கேள்விகள் இருந்தால் இடையில் கேளுங்கள்."],
  "Hinweis: Für die Folgefragen hilft mir eine KI (OpenAI), für die Auswertung am Ende eine weitere (Claude von Anthropic). E-Mail-Adressen, Telefonnummern und Links werden vorher entfernt.": ["Note: an AI (OpenAI) helps me with the follow-up questions, and another one (Claude by Anthropic) with the evaluation at the end. Email addresses, phone numbers and links are removed beforehand.", "குறிப்பு: தொடர் கேள்விகளுக்கு ஒரு AI (OpenAI) உதவுகிறது, இறுதியில் மதிப்பீட்டிற்கு மற்றொன்று (Anthropic இன் Claude). மின்னஞ்சல் முகவரிகள், தொலைபேசி எண்கள் மற்றும் இணைப்புகள் முன்பே நீக்கப்படுகின்றன."],
  "Zum Abschluss habe ich noch eine Bitte an dich: Was wünschst du dir von DSpora? Welche Features oder Ideen sollten wir unbedingt einbauen?": ["Finally I have one more request: what do you wish for from DSpora? Which features or ideas should we definitely build in?", "இறுதியாக ஒரு வேண்டுகோள்: DSpora விடமிருந்து நீங்கள் என்ன விரும்புகிறீர்கள்? எந்த அம்சங்கள் அல்லது யோசனைகளை நாங்கள் கண்டிப்பாகச் சேர்க்க வேண்டும்?"],
});

// ——— Onboarding: Zwischenfragen, Steckbrief, Gespräch (Phase 2), Abschluss ———
register({
  "Wenn etwas nicht mehr stimmt, erzähl mir hier einfach den neuen Stand. Einzelne Angaben kannst du in deinem Profil auch selbst entfernen.": ["If something is no longer true, simply tell me the new status here. You can also remove individual details yourself in your profile.", "ஏதாவது இனி சரியில்லை என்றால், புதிய நிலையை இங்கே சொல்லுங்கள். தனிப்பட்ட விவரங்களை உங்கள் சுயவிவரத்திலும் நீங்களே அகற்றலாம்."],
  "Steckbrief im Profil": ["Profile summary in your profile", "சுயவிவரத்தில் விவரச்சுருக்கம்"],
  "Nach der Anmeldung kannst du alles jederzeit in deinem Profil anpassen und mir im Gespräch Neues erzählen.": ["After signing in you can adjust everything in your profile at any time and tell me something new in the conversation.", "உள்நுழைந்த பிறகு எப்போது வேண்டுமானாலும் உங்கள் சுயவிவரத்தில் எல்லாவற்றையும் மாற்றலாம், உரையாடலில் புதியதைச் சொல்லலாம்."],
  "Aber zurück zu dir: {question}": ["But back to you: {question}", "ஆனால் உங்களிடம் திரும்பி வருவோம்: {question}"],
  "Einzelne Angaben entfernst du in deinem Profil unter „Dein Steckbrief“ mit dem ×. Dann sind sie auch wirklich weg. Wenn sich etwas geändert hat, erzähl mir hier gern den neuen Stand.": ["You remove individual details in your profile under “Your profile summary” with the ×. Then they are really gone. If something has changed, feel free to tell me the new status here.", "தனிப்பட்ட விவரங்களை உங்கள் சுயவிவரத்தில் “உங்கள் விவரச்சுருக்கம்” என்பதன் கீழ் × மூலம் அகற்றலாம். அப்போது அவை உண்மையிலேயே நீங்கிவிடும். ஏதாவது மாறியிருந்தால், புதிய நிலையை இங்கே சொல்லுங்கள்."],
  "Zum Steckbrief": ["To the profile summary", "விவரச்சுருக்கத்திற்கு"],
  "Nach der Anmeldung kannst du in deinem Profil unter „Dein Steckbrief“ jede Angabe mit dem × entfernen. Wenn sich etwas geändert hat, erzähl mir gern den neuen Stand.": ["After signing in you can remove any detail in your profile under “Your profile summary” with the ×. If something has changed, feel free to tell me the new status.", "உள்நுழைந்த பிறகு உங்கள் சுயவிவரத்தில் “உங்கள் விவரச்சுருக்கம்” என்பதன் கீழ் எந்த விவரத்தையும் × மூலம் அகற்றலாம். ஏதாவது மாறியிருந்தால், புதிய நிலையைச் சொல்லுங்கள்."],
  "Erzähl mir gern, was dir wichtig ist, wer du bist oder wonach du suchst.": ["Feel free to tell me what matters to you, who you are or what you are looking for.", "உங்களுக்கு முக்கியமானது என்ன, நீங்கள் யார், எதைத் தேடுகிறீர்கள் என்று சொல்லுங்கள்."],
  "Frag du mich": ["You ask me", "நீங்கள் என்னிடம் கேளுங்கள்"],
  "Das hast du mir mitgeteilt": ["You told me this", "இதை நீங்கள் எனக்குத் தெரிவித்தீர்கள்"],
  "Danke, das merke ich mir.": ["Thanks, I'll remember that.", "நன்றி, இதை நினைவில் வைத்துக்கொள்கிறேன்."],
  "Überspringen": ["Skip", "தவிர்"],
  "Danke, das erzählt schon viel über dich.": ["Thanks, that already says a lot about you.", "நன்றி, இது உங்களைப் பற்றி ஏற்கனவே நிறையச் சொல்கிறது."],
  "Ich glaube, ich habe dich jetzt schon richtig gut kennengelernt. Danke dir!": ["I think I have already gotten to know you really well. Thank you!", "உங்களை ஏற்கனவே நன்றாக அறிந்துகொண்டேன் என்று நினைக்கிறேன். நன்றி!"],
  "Kein Problem, dann etwas anderes:": ["No problem, then something else:", "பரவாயில்லை, அப்படியானால் வேறொன்று:"],
  "Das war schon richtig spannend! Möchtest du noch weiter erzählen, oder sollen wir das Gespräch später fortsetzen? Wir können gern noch länger reden.": ["That was really exciting! Would you like to keep telling me more, or shall we continue the conversation later? We're happy to talk longer.", "இது மிகவும் சுவாரஸ்யமாக இருந்தது! மேலும் சொல்ல விரும்புகிறீர்களா, அல்லது உரையாடலைப் பின்னர் தொடரலாமா? இன்னும் நீண்ட நேரம் பேசலாம்."],
  "Ich lerne dich gerade richtig gut kennen. Weiter erzählen, oder sollen wir später weitermachen?": ["I'm really getting to know you. Keep telling me, or shall we continue later?", "உங்களை நன்றாக அறிந்துகொள்கிறேன். தொடர்ந்து சொல்லுங்கள், அல்லது பின்னர் தொடரலாமா?"],
  "Gern, weiter erzählen": ["Gladly, I'll keep telling", "சரி, தொடர்ந்து சொல்கிறேன்"],
  "Super, dann weiter!": ["Great, let's continue!", "அருமை, தொடர்வோம்!"],
  "Später fortsetzen": ["Continue later", "பின்னர் தொடர்"],
  "Alles klar, wir setzen das Gespräch später fort. Du findest es dann in deinem Profil.": ["All right, we'll continue the conversation later. You'll find it in your profile.", "சரி, உரையாடலைப் பின்னர் தொடர்வோம். அதை உங்கள் சுயவிவரத்தில் காணலாம்."],
  "Einen Moment, ich speichere deine Antworten …": ["One moment, I'm saving your answers …", "ஒரு நிமிடம், உங்கள் பதில்களைச் சேமிக்கிறேன் …"],
  "Das hat leider nicht geklappt. Magst du es noch einmal versuchen?": ["Unfortunately that didn't work. Would you like to try again?", "துரதிர்ஷ்டவசமாக அது வெற்றிபெறவில்லை. மீண்டும் முயற்சிக்கிறீர்களா?"],
  "Fast geschafft! Zum Schluss bestätigst du deine E-Mail-Adresse. Ich schicke dir einen Link, mit dem du dich anmeldest und dein Profil gespeichert wird.": ["Almost done! Finally you confirm your email address. I'll send you a link that signs you in and saves your profile.", "கிட்டத்தட்ட முடிந்தது! இறுதியாக உங்கள் மின்னஞ்சல் முகவரியை உறுதிப்படுத்துங்கள். உங்களை உள்நுழையச் செய்து சுயவிவரத்தைச் சேமிக்கும் இணைப்பை அனுப்புகிறேன்."],
  "Perfekt, danke dir! Einen Moment, ich lege dein Profil an …": ["Perfect, thank you! One moment, I'm creating your profile …", "சரி, நன்றி! ஒரு நிமிடம், உங்கள் சுயவிவரத்தை உருவாக்குகிறேன் …"],
  "Deine Antworten sind gespeichert, nur die Fotos konnten leider nicht hochgeladen werden.": ["Your answers are saved, only the photos could unfortunately not be uploaded.", "உங்கள் பதில்கள் சேமிக்கப்பட்டன, புகைப்படங்களை மட்டும் பதிவேற்ற முடியவில்லை."],
  "Check dein Postfach: Ich habe dir einen Link an {value} geschickt. Mit einem Klick bist du drin, ganz ohne Passwort.": ["Check your inbox: I sent a link to {value}. One click and you're in, no password needed.", "உங்கள் இன்பாக்ஸைப் பாருங்கள்: {value} முகவரிக்கு இணைப்பை அனுப்பியுள்ளேன். ஒரு கிளிக்கில் உள்ளே வரலாம், கடவுச்சொல் தேவையில்லை."],
  "Schau auch im Spam-Ordner nach, falls nichts ankommt.": ["Also check your spam folder if nothing arrives.", "எதுவும் வரவில்லை என்றால் ஸ்பேம் கோப்புறையையும் பாருங்கள்."],
  "Gespräch": ["Conversation", "உரையாடல்"],
  "Finale": ["Finale", "நிறைவு"],
  "Phase 2": ["Phase 2", "கட்டம் 2"],
  "Frage {i} / {n}": ["Question {i} / {n}", "கேள்வி {i} / {n}"],
  "DSpora schreibt": ["DSpora is typing", "DSpora தட்டச்சு செய்கிறது"],
  "Testmodus": ["Test mode", "சோதனை முறை"],
  "← Zurück": ["← Back", "← பின்செல்"],
  "Anderes: schreib es selbst": ["Other: write it yourself", "மற்றவை: நீங்களே எழுதுங்கள்"],
  "Etwas anderes? Eigene Angabe": ["Something else? Your own entry", "வேறு ஏதாவதா? உங்கள் சொந்த உள்ளீடு"],
  "z. B. Gründerin, Product Manager, Entwickler": ["e.g. founder, product manager, developer", "எ.கா. நிறுவனர், தயாரிப்பு மேலாளர், உருவாக்குநர்"],
  "Ein anderes Ziel? Eigenes hinzufügen": ["Another goal? Add your own", "வேறு இலக்கா? உங்களுடையதைச் சேர்க்கவும்"],
  "z. B. Tennis": ["e.g. tennis", "எ.கா. டென்னிஸ்"],
  "z. B. Padel": ["e.g. padel", "எ.கா. பேடல்"],
  "z. B. Kochen": ["e.g. cooking", "எ.கா. சமையல்"],
  "z. B. Fotografie": ["e.g. photography", "எ.கா. புகைப்படக்கலை"],
  "z. B. Anime": ["e.g. anime", "எ.கா. அனிமே"],
  "z. B. Wandern": ["e.g. hiking", "எ.கா. மலையேற்றம்"],
  "z. B. Bouldern": ["e.g. bouldering", "எ.கா. பாறை ஏற்றம்"],
  "z. B. Podcasts": ["e.g. podcasts", "எ.கா. பாட்காஸ்ட்கள்"],
  "Eigener Begriff": ["Your own term", "உங்கள் சொந்தச் சொல்"],
  "Bis zu 5 insgesamt. Ähnliche Wörter erkenne ich selbst, du musst nicht dasselbe tippen wie andere.": ["Up to 5 in total. I recognize similar words myself, you don't have to type the same as others.", "மொத்தம் 5 வரை. ஒத்த சொற்களை நானே அறிவேன், மற்றவர்கள் தட்டச்சு செய்ததையே நீங்கள் தட்டச்ச வேண்டியதில்லை."],
  "z. B. Ehrlich": ["e.g. honest", "எ.கா. நேர்மையானவர்"],
  "z. B. Neugierig": ["e.g. curious", "எ.கா. ஆர்வமுள்ளவர்"],
  "z. B. Herzlich": ["e.g. warm-hearted", "எ.கா. அன்பானவர்"],
  "z. B. Ruhig": ["e.g. calm", "எ.கா. அமைதியானவர்"],
  "z. B. Offen": ["e.g. open", "எ.கா. திறந்த மனமுள்ளவர்"],
  "z. B. Ehrgeizig": ["e.g. ambitious", "எ.கா. இலட்சியமுள்ளவர்"],
  "z. B. Gelassen": ["e.g. composed", "எ.கா. நிதானமானவர்"],
  "z. B. Verspielt": ["e.g. playful", "எ.கா. விளையாட்டுத்தனமானவர்"],
  "Bis zu 5 insgesamt.": ["Up to 5 in total.", "மொத்தம் 5 வரை."],
  "Dein Spitzname oder Künstlername": ["Your nickname or stage name", "உங்கள் புனைப்பெயர் அல்லது கலைப்பெயர்"],
  "Erzähl frei heraus, was dir wichtig ist, wer du bist oder wonach du suchst …": ["Tell me freely what matters to you, who you are or what you are looking for …", "உங்களுக்கு முக்கியமானது என்ன, நீங்கள் யார், எதைத் தேடுகிறீர்கள் என்பதை மனம்திறந்து சொல்லுங்கள் …"],
  "Deine Antwort …": ["Your answer …", "உங்கள் பதில் …"],
  "Meine Wünsche und Ideen für DSpora …": ["My wishes and ideas for DSpora …", "DSpora க்கான என் விருப்பங்களும் யோசனைகளும் …"],
  "Jetzt anmelden & Profil speichern": ["Sign in & save profile", "இப்போது உள்நுழைந்து சுயவிவரத்தைச் சேமி"],
  "Andere Adresse oder erneut senden (in {n} s)": ["Other address or send again (in {n} s)", "வேறு முகவரி அல்லது மீண்டும் அனுப்பு ({n} வினாடியில்)"],
  "Link erneut senden / andere Adresse": ["Send link again / other address", "இணைப்பை மீண்டும் அனுப்பு / வேறு முகவரி"],
  "Kein Passwort nötig. Deine E-Mail-Adresse bleibt für andere unsichtbar.": ["No password needed. Your email address stays invisible to others.", "கடவுச்சொல் தேவையில்லை. உங்கள் மின்னஞ்சல் முகவரி மற்றவர்களுக்குத் தெரியாது."],
  "Erneut versuchen": ["Try again", "மீண்டும் முயற்சி"],
  "Eine Frage stellen": ["Ask a question", "ஒரு கேள்வி கேள்"],
  "Gespräch fortsetzen": ["Continue conversation", "உரையாடலைத் தொடர்"],
  "Das Gespräch wurde zurückgesetzt.": ["The conversation has been reset.", "உரையாடல் மீட்டமைக்கப்பட்டது."],
  "Weiter erzählen": ["Keep telling", "தொடர்ந்து சொல்"],
  "Das weiß ich aktuell über dich:": ["This is what I currently know about you:", "உங்களைப் பற்றி தற்போது நான் அறிந்தவை:"],
  "Das hast du mir erzählt:": ["This is what you told me:", "நீங்கள் எனக்குச் சொன்னவை:"],
  "Bisher weiß ich noch nicht viel über dich. Erzähl mir gern mehr, dann entsteht dein Steckbrief.": ["So far I don't know much about you. Tell me more and your profile summary will take shape.", "இதுவரை உங்களைப் பற்றி அதிகம் தெரியாது. மேலும் சொல்லுங்கள், உங்கள் விவரச்சுருக்கம் உருவாகும்."],
});

// ——— Antworten des Chats zu DSpora ———
register({
  "Unsere Mission lesen": ["Read our mission", "எங்கள் நோக்கத்தைப் படியுங்கள்"],
  "Zum Kontaktformular": ["To the contact form", "தொடர்புப் படிவத்திற்கு"],
  "Zur Datenschutzerklärung": ["To the privacy policy", "தனியுரிமைக் கொள்கைக்கு"],
  "Die Kernnutzung von DSpora ist für dich vollkommen kostenlos. Sollten wir die Plattform künftig durch ausgewählte Community-Partner oder dezente Sponsoren unterstützen, dient das laut unserer Mission nur dem Erhalt und der Weiterentwicklung des Projekts.": [
    "The core use of DSpora is completely free for you. Should we support the platform in future through selected community partners or discreet sponsors, then according to our mission that serves only to maintain and further develop the project.",
    "DSpora வின் முக்கியப் பயன்பாடு உங்களுக்கு முற்றிலும் இலவசம். எதிர்காலத்தில் தேர்ந்தெடுக்கப்பட்ட சமூகக் கூட்டாளிகள் அல்லது கண்ணியமான ஆதரவாளர்கள் மூலம் தளத்தை ஆதரித்தால், அது எங்கள் நோக்கத்தின்படி திட்டத்தைப் பராமரிக்கவும் மேம்படுத்தவும் மட்டுமே.",
  ],
  "Anonymität ist bei uns eine Option, kein Zwang: Im Chat gibst du nur einen Spitznamen an, so bleibst du geschützt und kannst dich erst öffnen, wenn der passende Freundeskreis gefunden ist. Wer dein Profil sehen darf, stellst du selbst ein.": [
    "Anonymity is an option with us, not a requirement: in the chat you only give a nickname, so you stay protected and can open up once the right circle of friends is found. You decide yourself who may see your profile.",
    "அடையாளமின்மை எங்களிடம் ஒரு விருப்பம், கட்டாயம் அல்ல: அரட்டையில் புனைப்பெயரை மட்டுமே தருகிறீர்கள், இதனால் பாதுகாப்பாக இருந்து, பொருத்தமான நண்பர் வட்டம் கிடைத்த பிறகு உங்களைத் திறக்கலாம். உங்கள் சுயவிவரத்தை யார் பார்க்கலாம் என்பதை நீங்களே தீர்மானிக்கிறீர்கள்.",
  ],
  "Sobald sich 100 Personen in einer Region eintragen, öffnet sich der Hub dieser Region. Es gibt Hubs für NRW, Rhein-Main, Baden-Württemberg, Bayern & Allgäu, Hauptstadt & Ost, Hamburg & Nord, die Schweiz und Österreich. Ein festes Startdatum nennt die Webseite nicht. Du kannst den Link teilen, so wird dein Hub schneller freigeschaltet.": [
    "As soon as 100 people sign up in a region, the hub of that region opens. There are hubs for NRW, Rhine-Main, Baden-Württemberg, Bavaria & Allgäu, Capital & East, Hamburg & North, Switzerland and Austria. The website names no fixed start date. You can share the link, so your hub is unlocked faster.",
    "ஒரு பகுதியில் 100 பேர் பதிவு செய்தவுடன் அந்தப் பகுதியின் மையம் திறக்கும். NRW, ரைன்-மைன், பாடன்-வுர்ட்டம்பெர்க், பவேரியா & ஆல்கோய், தலைநகர் & கிழக்கு, ஹாம்பர்க் & வடக்கு, சுவிட்சர்லாந்து மற்றும் ஆஸ்திரியாவுக்கு மையங்கள் உள்ளன. இணையதளம் குறிப்பிட்ட தொடக்கத் தேதியைக் கூறவில்லை. இணைப்பைப் பகிரலாம், அப்போது உங்கள் மையம் விரைவாகத் திறக்கும்.",
  ],
  "Du wählst die Gruppengröße, die zu deinem sozialen Akku passt. Das Duo (2er Gruppe) ist ideal für Workouts, Joggen oder Business-Kontakte. Die Crew (4er Gruppe) passt zu Spieleabenden, Gaming oder Veranstaltungen. Der Squad (8er Gruppe) eignet sich für lebendige Events, Ausflüge oder Tanzgruppen.": [
    "You choose the group size that fits your social battery. The duo (group of 2) is ideal for workouts, jogging or business contacts. The crew (group of 4) suits game nights, gaming or events. The squad (group of 8) is good for lively events, trips or dance groups.",
    "உங்கள் சமூகச் சக்திக்குப் பொருந்தும் குழு அளவை நீங்கள் தேர்ந்தெடுக்கிறீர்கள். இருவர் (2 பேர் குழு) உடற்பயிற்சி, ஓட்டம் அல்லது வணிகத் தொடர்புகளுக்கு ஏற்றது. குழு (4 பேர்) விளையாட்டு மாலைகள், கேமிங் அல்லது நிகழ்வுகளுக்குப் பொருந்தும். பெரிய குழு (8 பேர்) உற்சாகமான நிகழ்வுகள், பயணங்கள் அல்லது நடனக் குழுக்களுக்கு ஏற்றது.",
  ],
  "Der KI-Persönlichkeits-Check ist kein starrer Fragebogen, sondern ein entspanntes Gespräch. Wie lange es dauert, liegt ganz bei dir. Daraus finden wir dein Match für Duo, Crew oder Squad. Deine Optik ist dabei völlig irrelevant, es zählt nur, dass deine Persönlichkeit zu deinen Leuten passt.": [
    "The AI personality check is not a rigid questionnaire but a relaxed conversation. How long it takes is entirely up to you. From it we find your match for duo, crew or squad. Your looks are completely irrelevant, all that counts is that your personality fits your people.",
    "AI ஆளுமைச் சோதனை கடினமான வினாத்தாள் அல்ல, அது ஒரு தளர்வான உரையாடல். எவ்வளவு நேரம் ஆகும் என்பது முழுவதும் உங்கள் விருப்பம். அதிலிருந்து இருவர், குழு அல்லது பெரிய குழுவுக்கான உங்கள் இணைப்பைக் கண்டறிகிறோம். உங்கள் தோற்றம் முற்றிலும் பொருட்டல்ல, உங்கள் ஆளுமை உங்கள் மக்களுக்குப் பொருந்துவதே முக்கியம்.",
  ],
  "DSpora ist ein Herzensprojekt für die tamilische Community im deutschsprachigen Raum. Wir glauben nicht an den reinen Zufall, wenn es um echte Freundschaften geht, und wollen Menschen mit denselben Wurzeln und passenden Interessen zusammenbringen, damit niemand im Stillen verloren geht.": [
    "DSpora is a passion project for the Tamil community in the German-speaking region. We don't believe in pure chance when it comes to real friendships, and we want to bring people with the same roots and matching interests together so that nobody gets lost in silence.",
    "DSpora ஜெர்மன் மொழி பேசும் பகுதியிலுள்ள தமிழ்ச் சமூகத்திற்கான ஒரு இதயப்பூர்வமான திட்டம். உண்மையான நட்புகள் என்று வரும்போது வெறும் தற்செயலை நாங்கள் நம்புவதில்லை; ஒரே வேர்களும் பொருந்தும் ஆர்வங்களும் உள்ளவர்களை இணைக்க விரும்புகிறோம், இதனால் யாரும் அமைதியாகத் தொலைந்துபோகாமல் இருக்கட்டும்.",
  ],
  "DSpora wurde exklusiv für die tamilische Community in Deutschland, Österreich und der Schweiz ins Leben gerufen.": ["DSpora was created exclusively for the Tamil community in Germany, Austria and Switzerland.", "DSpora ஜெர்மனி, ஆஸ்திரியா மற்றும் சுவிட்சர்லாந்திலுள்ள தமிழ்ச் சமூகத்திற்காகவே உருவாக்கப்பட்டது."],
  "DSpora ist nicht nur für Freundschaften da: Du kannst die Plattform auch für Business-Kontakte nutzen, zum Beispiel, um Co-Founder, Partner oder Mentoren zu finden. Dafür wählst du im Onboarding die Richtung Business-Community und gibst Branche, Rolle und Ziele an. Ein kurzes Light-CV kannst du später in deinem Profil ergänzen, und du bestimmst selbst, wer dich sehen darf.": [
    "DSpora is not only for friendships: you can also use the platform for business contacts, for example to find co-founders, partners or mentors. For that you choose the business community direction during onboarding and enter industry, role and goals. You can add a short light CV later in your profile, and you decide yourself who may see you.",
    "DSpora நட்புகளுக்கு மட்டுமல்ல: இணை நிறுவனர்கள், கூட்டாளிகள் அல்லது வழிகாட்டிகளைக் கண்டறிவது போன்ற வணிகத் தொடர்புகளுக்கும் தளத்தைப் பயன்படுத்தலாம். அதற்கு அறிமுகத்தில் வணிக சமூகம் என்ற திசையைத் தேர்ந்தெடுத்து துறை, பங்கு மற்றும் இலக்குகளை உள்ளிடுகிறீர்கள். ஒரு சுருக்கமான சுயவிவரத்தை பின்னர் உங்கள் சுயவிவரத்தில் சேர்க்கலாம், யார் உங்களைப் பார்க்கலாம் என்பதை நீங்களே தீர்மானிக்கிறீர்கள்.",
  ],
  "Ein Passwort brauchst du bei DSpora nicht. Du meldest dich über einen Link an, den wir dir per E-Mail schicken. In deinem Profil kannst du außerdem einen Passkey einrichten, um dich mit Face ID oder Touch ID anzumelden. Dein Konto kannst du dort auch jederzeit selbst löschen.": [
    "You don't need a password at DSpora. You sign in with a link that we send you by email. In your profile you can also set up a passkey to sign in with Face ID or Touch ID. You can also delete your account there yourself at any time.",
    "DSpora வில் கடவுச்சொல் தேவையில்லை. நாங்கள் மின்னஞ்சலில் அனுப்பும் இணைப்பு மூலம் உள்நுழைகிறீர்கள். உங்கள் சுயவிவரத்தில் Face ID அல்லது Touch ID மூலம் உள்நுழைய Passkey ஐயும் அமைக்கலாம். அங்கேயே உங்கள் கணக்கை எப்போது வேண்டுமானாலும் நீங்களே நீக்கலாம்.",
  ],
  "Uns geht es um echte Treffen statt endlosem Hin-und-her-Schreiben: Von der Webseite aus geht es direkt zum gemeinsamen Treffen, Freundschaften entstehen vor Ort. Die KI vernetzt dich dafür mit Leuten aus deiner Nähe, die ähnliche Interessen haben, zum Beispiel Sport, Gaming oder Kultur.": [
    "We care about real meetings instead of endless back-and-forth writing: from the website it goes straight to meeting in person, friendships are formed on site. For that the AI connects you with people near you who have similar interests, for example sports, gaming or culture.",
    "முடிவற்ற செய்தி பரிமாற்றத்திற்குப் பதிலாக உண்மையான சந்திப்புகளே எங்கள் நோக்கம்: இணையதளத்திலிருந்து நேரடியாக ஒன்றாகச் சந்திப்பதற்குச் செல்கிறது, நட்புகள் நேரில் உருவாகின்றன. இதற்காக AI உங்களை அருகிலுள்ள, ஒத்த ஆர்வங்கள் உள்ளவர்களுடன் இணைக்கிறது, உதாரணமாக விளையாட்டு, கேமிங் அல்லது கலாச்சாரம்.",
  ],
  "Das Ganze bleibt anfangs vollkommen anonym und ganz ohne Spam. Deine E-Mail-Adresse bleibt für andere unsichtbar.": ["The whole thing stays completely anonymous at first and entirely free of spam. Your email address stays invisible to others.", "இவை அனைத்தும் தொடக்கத்தில் முற்றிலும் அடையாளமின்றி, ஸ்பேம் இல்லாமல் இருக்கும். உங்கள் மின்னஞ்சல் முகவரி மற்றவர்களுக்குத் தெரியாது."],
  "Deine E-Mail-Adresse bleibt für andere unsichtbar, und dein Konto kannst du in deinem Profil jederzeit selbst löschen. Alles Weitere zum Umgang mit Daten findest du in der Datenschutzerklärung.": ["Your email address stays invisible to others, and you can delete your account yourself in your profile at any time. You'll find everything else about how data is handled in the privacy policy.", "உங்கள் மின்னஞ்சல் முகவரி மற்றவர்களுக்குத் தெரியாது, உங்கள் சுயவிவரத்தில் எப்போது வேண்டுமானாலும் கணக்கை நீங்களே நீக்கலாம். தரவு கையாளுதல் பற்றிய மற்ற அனைத்தையும் தனியுரிமைக் கொள்கையில் காணலாம்."],
  "Zu den Personen hinter DSpora kann ich dir hier keine Angaben machen, ich möchte nichts erfinden. Auf der Webseite steht nur, dass DSpora ein Herzensprojekt für die Community ist. Für alles Weitere schreib uns gern über das Kontaktformular.": ["I can't give you any details here about the people behind DSpora, I don't want to make anything up. The website only says that DSpora is a passion project for the community. For anything else, feel free to write to us via the contact form.", "DSpora வின் பின்னால் இருப்பவர்களைப் பற்றி இங்கே எந்த விவரமும் தர முடியாது, எதையும் கற்பனை செய்ய விரும்பவில்லை. DSpora சமூகத்திற்கான இதயப்பூர்வமான திட்டம் என்று மட்டுமே இணையதளம் கூறுகிறது. மற்றவற்றுக்கு தொடர்புப் படிவம் வழியாக எங்களுக்கு எழுதுங்கள்."],
  "Du erreichst uns über das Kontaktformular. Hier im Chat geht es in erster Linie darum, dich kennenzulernen.": ["You can reach us via the contact form. Here in the chat it is primarily about getting to know you.", "தொடர்புப் படிவம் மூலம் எங்களைத் தொடர்பு கொள்ளலாம். இந்த அரட்டையில் முக்கியமாக உங்களை அறிந்துகொள்வதே நோக்கம்."],
  "Dazu habe ich leider keine gesicherte Information, und ich möchte nichts erfinden. Hier geht es in erster Linie darum, dich kennenzulernen. Fragen, die nicht zum Thema gehören, kann ich deshalb nicht beantworten. Schreib uns dazu gern über das Kontaktformular.": ["Unfortunately I have no reliable information on that, and I don't want to make anything up. Here it is primarily about getting to know you. I therefore can't answer questions that are off topic. Feel free to write to us about it via the contact form.", "அதைப் பற்றி என்னிடம் உறுதியான தகவல் இல்லை, எதையும் கற்பனை செய்ய விரும்பவில்லை. இங்கு முக்கியமாக உங்களை அறிந்துகொள்வதே நோக்கம். எனவே தலைப்புக்குப் புறம்பான கேள்விகளுக்கு என்னால் பதிலளிக்க முடியாது. அதற்கு தொடர்புப் படிவம் வழியாக எங்களுக்கு எழுதுங்கள்."],
});

// ——— Allgemeine Folgefragen (ohne KI) ———
register({
  "Was zeichnet für dich eine echte Freundschaft aus?": ["What makes a real friendship for you?", "உங்களுக்கு உண்மையான நட்பு என்பது எதனால் அமைகிறது?"],
  "Woran merkst du, dass dir jemand guttut?": ["How do you notice that someone is good for you?", "ஒருவர் உங்களுக்கு நல்லது என்பதை எப்படி உணர்கிறீர்கள்?"],
  "Was würdest du an einem freien Wochenende am liebsten mit neuen Leuten unternehmen?": ["What would you most like to do with new people on a free weekend?", "ஓய்வான வார இறுதியில் புதிய மனிதர்களுடன் என்ன செய்ய விரும்புவீர்கள்?"],
  "Bist du eher der Typ für einen großen Freundeskreis oder für wenige enge Vertraute?": ["Are you more the type for a large circle of friends or for a few close confidants?", "பெரிய நண்பர் வட்டம் உங்களுக்குப் பிடிக்குமா, அல்லது சில நெருங்கிய நம்பிக்கையாளர்களா?"],
  "Wie verbringst du am liebsten einen ruhigen Abend?": ["How do you like to spend a quiet evening?", "அமைதியான மாலையை எப்படிக் கழிக்க விரும்புகிறீர்கள்?"],
  "Planst du Treffen gern langfristig, oder entscheidest du eher spontan?": ["Do you like to plan meetings long in advance, or do you decide more spontaneously?", "சந்திப்புகளை நீண்ட காலம் முன்பே திட்டமிட விரும்புகிறீர்களா, அல்லது தன்னிச்சையாக முடிவு செய்கிறீர்களா?"],
  "Welche Rolle spielt Humor in deinen Freundschaften?": ["What role does humor play in your friendships?", "உங்கள் நட்புகளில் நகைச்சுவை எந்தப் பங்கு வகிக்கிறது?"],
  "Was bringt dich in einer Gruppe zum Aufleben, und was lässt dich eher still werden?": ["What makes you come alive in a group, and what makes you go quiet?", "ஒரு குழுவில் உங்களை உற்சாகப்படுத்துவது எது, அமைதியாக்குவது எது?"],
  "Wie war dein letztes richtig schönes Treffen mit Freunden?": ["What was your last really nice get-together with friends like?", "நண்பர்களுடன் உங்கள் கடைசி உண்மையிலேயே இனிமையான சந்திப்பு எப்படி இருந்தது?"],
  "Was muss ein erstes Treffen haben, damit du dich wohlfühlst, und was wäre ein No-Go?": ["What does a first meeting need so that you feel comfortable, and what would be a no-go?", "நீங்கள் சௌகரியமாக உணர முதல் சந்திப்பில் என்ன இருக்க வேண்டும், எது ஏற்றுக்கொள்ள முடியாதது?"],
  "Welche Eigenschaft schätzt du an Menschen am meisten?": ["Which quality do you value most in people?", "மனிதர்களிடம் எந்தப் பண்பை நீங்கள் அதிகம் மதிக்கிறீர்கள்?"],
  "Wofür bist du in deinem Freundeskreis bekannt?": ["What are you known for in your circle of friends?", "உங்கள் நண்பர் வட்டத்தில் நீங்கள் எதற்காக அறியப்படுகிறீர்கள்?"],
  "Gibt es etwas, das du schon immer mal mit anderen ausprobieren wolltest?": ["Is there something you've always wanted to try with others?", "மற்றவர்களுடன் எப்போதாவது முயற்சிக்க விரும்பிய ஏதேனும் ஒன்று உள்ளதா?"],
});

// ——— Eingabefelder (Alter, Begriffe) ———
register({
  "{n} von {max} gewählt": ["{n} of {max} selected", "{max} இல் {n} தேர்ந்தெடுக்கப்பட்டன"],
  "{n} von {max} gewählt (mindestens {min})": ["{n} of {max} selected (at least {min})", "{max} இல் {n} தேர்ந்தெடுக்கப்பட்டன (குறைந்தது {min})"],
  "Bitte gib mindestens {min} an.": ["Please enter at least {min}.", "குறைந்தது {min} உள்ளிடவும்."],
  "Höchstens {max} Einträge insgesamt.": ["At most {max} entries in total.", "மொத்தம் அதிகபட்சம் {max} உள்ளீடுகள்."],
  "„{word}“ ist ungültig: 2 bis 30 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["“{word}” is invalid: 2 to 30 characters, only letters, numbers and simple characters.", "“{word}” செல்லாது: 2 முதல் 30 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
  "Eigener Begriff {n}": ["Your own term {n}", "உங்கள் சொந்தச் சொல் {n}"],
  "Bitte gib dein Alter als Zahl zwischen {min} und {max} an.": ["Please enter your age as a number between {min} and {max}.", "உங்கள் வயதை {min} முதல் {max} வரையிலான எண்ணாக உள்ளிடவும்."],
  "Bitte gib beide Zahlen zwischen {min} und {max} an.": ["Please enter both numbers between {min} and {max}.", "{min} முதல் {max} வரையிலான இரண்டு எண்களையும் உள்ளிடவும்."],
  "„Von“ darf nicht größer sein als „bis“.": ["“From” must not be greater than “to”.", "தொடக்க வயது இறுதி வயதை விடப் பெரிதாக இருக்கக் கூடாது."],
  "Gewünschtes Alter von": ["Preferred age from", "விரும்பும் வயது முதல்"],
  "Gewünschtes Alter bis": ["Preferred age up to", "விரும்பும் வயது வரை"],
});

register({
  "2 bis 24 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["2 to 24 characters, only letters, numbers and simple characters.", "2 முதல் 24 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
});

// ——— Übersetzen im Chat ———
register({
  "Übersetzen": ["Translate", "மொழிபெயர்"],
  "Übersetze …": ["Translating …", "மொழிபெயர்க்கிறது …"],
  "Übersetzt aus {lang}": ["Translated from {lang}", "{lang} மொழியிலிருந்து மொழிபெயர்க்கப்பட்டது"],
  "Übersetzung ausblenden": ["Hide translation", "மொழிபெயர்ப்பை மறை"],
  "Übersetzung fehlgeschlagen": ["Translation failed", "மொழிபெயர்ப்பு தோல்வியடைந்தது"],
  "Schon in deiner Sprache": ["Already in your language", "ஏற்கனவே உங்கள் மொழியில்"],
  "Automatisch übersetzen": ["Translate automatically", "தானாக மொழிபெயர்"],
  "Übersetzt per KI, nur die einzelne Nachricht wird dafür an die KI geschickt.": ["Translated by AI; only the single message is sent to the AI for this.", "AI மூலம் மொழிபெயர்க்கப்படுகிறது; இதற்காக தனிப்பட்ட செய்தி மட்டுமே AI க்கு அனுப்பப்படுகிறது."],
  "einer anderen Sprache": ["another language", "வேறொரு மொழி"],
  "Dein Match hat den Chat verlassen. Dieser Chat ist beendet.": ["Your match has left the chat. This chat has ended.", "உங்கள் இணைப்பு அரட்டையை விட்டு வெளியேறியது. இந்த அரட்டை முடிந்தது."],
  "Eine Person hat den Chat verlassen.": ["One person has left the chat.", "ஒருவர் அரட்டையை விட்டு வெளியேறினார்."],
});

// ——— Onboarding: Karten-Ablauf, Gespräch, Zustimmung ———
register({
  "Willkommen bei DSpora. Lass uns herausfinden, was dir wichtig ist.": ["Welcome to DSpora. Let's find out what matters to you.", "DSpora விற்கு வரவேற்கிறோம். உங்களுக்கு எது முக்கியம் என்பதைக் கண்டறிவோம்."],
  "Ein paar kurze Fragen (etwa 2 Minuten), die alle beantwortet werden müssen, damit wir passende Leute für dich finden. Danach kannst du freiwillig mit mir weiterreden.": ["A few short questions (about 2 minutes) that all need an answer so we can find the right people for you. After that you can keep talking with me, if you like.", "சில சிறிய கேள்விகள் (சுமார் 2 நிமிடங்கள்). உங்களுக்குப் பொருத்தமானவர்களைக் கண்டறிய அனைத்திற்கும் பதில் அளிக்க வேண்டும். அதன் பிறகு விருப்பமிருந்தால் என்னுடன் தொடர்ந்து பேசலாம்."],
  "Wonach suchst du bei DSpora?": ["What are you looking for at DSpora?", "DSpora வில் நீங்கள் எதைத் தேடுகிறீர்கள்?"],
  "In welcher Gruppengröße möchtest du Leute treffen?": ["In what group size would you like to meet people?", "எந்த அளவிலான குழுவில் மக்களைச் சந்திக்க விரும்புகிறீர்கள்?"],
  "Welches Geschlecht hast du? Du kannst auch etwas Eigenes schreiben.": ["What is your gender? You can also write something of your own.", "உங்கள் பாலினம் என்ன? உங்கள் சொந்தமாகவும் எழுதலாம்."],
  "Welche Freundschaften suchst du?": ["What kind of friendships are you looking for?", "எப்படிப்பட்ட நட்புகளைத் தேடுகிறீர்கள்?"],
  "Welche Gruppe suchst du? Beantworte es so, wie es für dich passt.": ["Which group are you looking for? Answer however fits you.", "எந்தக் குழுவைத் தேடுகிறீர்கள்? உங்களுக்குப் பொருந்துவது போல் பதிலளிக்கலாம்."],
  "Welche Altersspanne passt dir bei den anderen? Du kannst die Zahlen anpassen.": ["Which age range suits you for the others? You can adjust the numbers.", "மற்றவர்களுக்கு எந்த வயது வரம்பு உங்களுக்குப் பொருந்தும்? எண்களை மாற்றிக்கொள்ளலாம்."],
  "In welcher Branche oder welchem Sektor bist du unterwegs?": ["Which industry or sector are you in?", "நீங்கள் எந்தத் துறையில் இருக்கிறீர்கள்?"],
  "Welcher Vibe beschreibt dich am besten? Auch hier gern eigene Wörter.": ["Which vibe describes you best? Feel free to use your own words here too.", "எந்த உணர்வு உங்களை சிறப்பாக விவரிக்கிறது? இங்கும் உங்கள் சொந்த வார்த்தைகளைப் பயன்படுத்தலாம்."],
  "Wie sollen wir dich nennen? Ein Spitzname oder Künstlername reicht, so kannst du anonym bleiben. Deinen echten Namen kannst du später im Profil ergänzen.": ["What should we call you? A nickname or stage name is enough, so you can stay anonymous. You can add your real name later in your profile.", "உங்களை எப்படி அழைப்பது? புனைப்பெயர் அல்லது கலைப்பெயர் போதும், இதனால் அடையாளமின்றி இருக்கலாம். உங்கள் உண்மையான பெயரை பின்னர் சுயவிவரத்தில் சேர்க்கலாம்."],
  "Basis-Profil erstellt.": ["Basic profile created.", "அடிப்படை சுயவிவரம் உருவாக்கப்பட்டது."],
  "Möchtest du dein Profil durch ein kurzes Gespräch schärfen, damit unser System noch tiefgründigere Matches für dich findet?": ["Would you like to sharpen your profile with a short conversation so our system can find even deeper matches for you?", "உங்கள் சுயவிவரத்தை ஒரு சிறிய உரையாடல் மூலம் மேம்படுத்த விரும்புகிறீர்களா? அப்போது எங்கள் அமைப்பு உங்களுக்கு இன்னும் ஆழமான பொருத்தங்களைக் கண்டறியும்."],
  "Ja, Gespräch starten": ["Yes, start the conversation", "ஆம், உரையாடலைத் தொடங்கு"],
  "Nein, direkt zum Hub": ["No, straight to the hub", "இல்லை, நேரடியாக ஹப்புக்கு"],
  "Los geht's. Du kannst jede Frage überspringen.": ["Let's go. You can skip any question.", "தொடங்குவோம். எந்தக் கேள்வியையும் தவிர்க்கலாம்."],
  "Du hast angegeben, dass du im Bereich {topic} unterwegs bist. Was reizt dich daran am meisten?": ["You said you work in {topic}. What appeals to you most about it?", "நீங்கள் {topic} துறையில் இருப்பதாகக் கூறினீர்கள். அதில் உங்களை மிகவும் ஈர்ப்பது என்ன?"],
  "Du hast {topic} als Interesse angegeben. Was gefällt dir daran am meisten?": ["You listed {topic} as an interest. What do you like most about it?", "நீங்கள் {topic} ஐ ஒரு ஆர்வமாகக் குறிப்பிட்டீர்கள். அதில் உங்களுக்கு மிகவும் பிடித்தது என்ன?"],
  "Was machst du am liebsten in deiner Freizeit?": ["What do you like to do most in your free time?", "ஓய்வு நேரத்தில் நீங்கள் மிகவும் விரும்பிச் செய்வது என்ன?"],
  "Danke, das hilft mir schon sehr weiter. Möchtest du noch weiter erzählen, oder sollen wir das Gespräch später fortsetzen?": ["Thanks, that already helps me a lot. Would you like to keep telling me more, or should we continue the conversation later?", "நன்றி, இது எனக்கு ஏற்கனவே மிகவும் உதவுகிறது. இன்னும் தொடர்ந்து சொல்ல விரும்புகிறீர்களா, அல்லது உரையாடலைப் பின்னர் தொடரலாமா?"],
  "Kein Problem, du musst nicht auf alles antworten. Möchtest du weitermachen oder das Gespräch später fortsetzen?": ["No problem, you don't have to answer everything. Would you like to continue, or pick the conversation up later?", "பரவாயில்லை, எல்லாவற்றிற்கும் பதில் சொல்ல வேண்டியதில்லை. தொடர விரும்புகிறீர்களா, அல்லது உரையாடலைப் பின்னர் தொடரலாமா?"],
  "KI-Analyse aktiv. Sensible Daten werden automatisch gefiltert.": ["AI analysis active. Sensitive data is filtered automatically.", "AI பகுப்பாய்வு செயலில் உள்ளது. முக்கியமான தரவுகள் தானாகவே வடிகட்டப்படுகின்றன."],
  "KI-Analyse und Datenschutz": ["AI analysis and privacy", "AI பகுப்பாய்வும் தரவுப் பாதுகாப்பும்"],
  "Deine Eingaben werden von unserem KI-System analysiert, um perfekte Matches zu finden. E-Mails, Nummern und Links werden vor der Verarbeitung automatisch gelöscht.": ["Your input is analyzed by our AI system to find perfect matches. Emails, numbers and links are automatically deleted before processing.", "சரியான பொருத்தங்களைக் கண்டறிய உங்கள் உள்ளீடுகள் எங்கள் AI அமைப்பால் பகுப்பாய்வு செய்யப்படுகின்றன. மின்னஞ்சல்கள், எண்கள் மற்றும் இணைப்புகள் செயலாக்கத்திற்கு முன் தானாகவே நீக்கப்படும்."],
  "← Startseite": ["← Home", "← முகப்பு"],
  "Fast geschafft!": ["Almost there!", "கிட்டத்தட்ட முடிந்தது!"],
  "Zum Schluss bestätigst du deine E-Mail-Adresse. Ich schicke dir einen Link, mit dem du dich anmeldest und dein Profil gespeichert wird.": ["Finally, you confirm your email address. I'll send you a link that signs you in and saves your profile.", "கடைசியாக உங்கள் மின்னஞ்சல் முகவரியை உறுதிப்படுத்துங்கள். நீங்கள் உள்நுழைந்து உங்கள் சுயவிவரம் சேமிக்கப்பட ஒரு இணைப்பை அனுப்புகிறேன்."],
  "Check dein Postfach.": ["Check your inbox.", "உங்கள் இன்பாக்ஸைப் பாருங்கள்."],
  "Ich habe dir einen Link an {value} geschickt. Mit einem Klick bist du drin, ganz ohne Passwort.": ["I sent a link to {value}. One click and you're in, no password needed.", "{value} முகவரிக்கு ஒரு இணைப்பை அனுப்பியுள்ளேன். ஒரு கிளிக்கில் உள்ளே வரலாம், கடவுச்சொல் தேவையில்லை."],
  "Ich akzeptiere die {link}. (DSpora nutzt intelligente KI-Analysen für dein Matching – E-Mails, Nummern und Links werden zu deinem Schutz vor der Verarbeitung automatisch blockiert).": ["I accept the {link}. (DSpora uses intelligent AI analysis for your matching – emails, numbers and links are automatically blocked before processing to protect you).", "நான் {link} ஏற்கிறேன். (DSpora உங்கள் பொருத்தத்திற்காக புத்திசாலித்தனமான AI பகுப்பாய்வுகளைப் பயன்படுத்துகிறது – உங்கள் பாதுகாப்புக்காக மின்னஞ்சல்கள், எண்கள் மற்றும் இணைப்புகள் செயலாக்கத்திற்கு முன் தானாகவே தடுக்கப்படும்)."],
  "Datenschutzbestimmungen": ["privacy policy", "தரவுப் பாதுகாப்பு விதிமுறைகளை"],
  "Bitte bestätige die Datenschutzbestimmungen.": ["Please accept the privacy policy.", "தயவுசெய்து தரவுப் பாதுகாப்பு விதிமுறைகளை ஏற்றுக்கொள்ளுங்கள்."],
  "Bevor es weitergeht": ["Before we continue", "தொடர்வதற்கு முன்"],
  "Bitte bestätige einmal die Datenschutzbestimmungen, damit wir dein Profil verwenden dürfen.": ["Please confirm the privacy policy once so that we may use your profile.", "உங்கள் சுயவிவரத்தைப் பயன்படுத்த நாங்கள் அனுமதி பெற, தரவுப் பாதுகாப்பு விதிமுறைகளை ஒருமுறை உறுதிப்படுத்துங்கள்."],
  "Welche Hobbys hast du, über die wir noch nicht gesprochen haben?": ["Which hobbies do you have that we haven't talked about yet?", "நாம் இன்னும் பேசாத எந்த பொழுதுபோக்குகள் உங்களுக்கு உள்ளன?"],
  "Welche Musik hörst du am liebsten?": ["What music do you like to listen to most?", "நீங்கள் எந்த வகை இசையை அதிகம் கேட்க விரும்புகிறீர்கள்?"],
  "Welche Filme oder Serien schaust du gern?": ["Which films or series do you enjoy watching?", "நீங்கள் எந்தத் திரைப்படங்களை அல்லது தொடர்களைப் பார்க்க விரும்புகிறீர்கள்?"],
  "Verbringst du deine Zeit lieber draußen oder drinnen?": ["Do you prefer spending your time outdoors or indoors?", "நேரத்தை வெளியில் செலவிடுவது பிடிக்குமா, உள்ளே இருப்பது பிடிக்குமா?"],
  "Welches Essen magst du am liebsten?": ["What food do you like most?", "உங்களுக்கு மிகவும் பிடித்த உணவு எது?"],
});
