import type { Language } from "@/lib/translations";

// Übersetzungen für die Oberfläche im Mitgliederbereich (Profil, Profilseiten, Chat-Übersicht, Anmeldung).
// Der Schlüssel ist der deutsche Text, wie er im Code steht. Platzhalter wie {name} werden eingesetzt.
// Nicht übersetzt werden: der Chat selbst (Nachrichten, Eisbrecher), das Onboarding-Gespräch, Rechtstexte und der Admin-Bereich.
// Fehlt ein Eintrag, bleibt der deutsche Text stehen.
export type Vars = Record<string, string | number>;

type Entry = { en: string; ta: string };

export const UI: Record<string, Entry> = {};

function fill(text: string, vars?: Vars): string {
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}

export function translateUi(de: string, language: Language, vars?: Vars): string {
  if (language === "de") return fill(de, vars);
  const entry = UI[de];
  return fill(entry ? entry[language] : de, vars);
}

/** Beschriftung einer Auswahlliste in der gewählten Sprache (Texte kommen aus lib/onboarding.ts). */
export function register(entries: Record<string, [string, string]>): void {
  for (const k of Object.keys(entries)) UI[k] = { en: entries[k][0], ta: entries[k][1] };
}

// ——— Allgemein ———
register({
  "Abbrechen": ["Cancel", "ரத்து செய்"],
  "Bearbeiten": ["Edit", "திருத்து"],
  "Speichern": ["Save", "சேமி"],
  "Speichere …": ["Saving …", "சேமிக்கிறது …"],
  "Gespeichert.": ["Saved.", "சேமிக்கப்பட்டது."],
  "Weiter": ["Next", "தொடர்"],
  "Löschen": ["Delete", "நீக்கு"],
  "Lösche …": ["Deleting …", "நீக்குகிறது …"],
  "Entfernen": ["Remove", "அகற்று"],
  "Schließen": ["Close", "மூடு"],
  "Hinzufügen": ["Add", "சேர்"],
  "Ja": ["Yes", "ஆம்"],
  "Nein": ["No", "இல்லை"],
  "Prüfen": ["Check", "சரிபார்"],
  "Übernehmen": ["Apply", "ஏற்றுக்கொள்"],
  "bis": ["to", "வரை"],
  "von": ["from", "முதல்"],
  "Anderes": ["Other", "மற்றவை"],
  "Sende …": ["Sending …", "அனுப்புகிறது …"],
  "Keine Verbindung. Bitte versuch es noch einmal.": ["No connection. Please try again.", "இணைப்பு இல்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்."],
  "Speichern hat nicht geklappt.": ["Saving didn't work.", "சேமிக்க முடியவில்லை."],
  "Das hat nicht geklappt.": ["That didn't work.", "அது வெற்றிபெறவில்லை."],
  "Bitte melde dich zuerst an.": ["Please sign in first.", "முதலில் உள்நுழையவும்."],
  "Chat": ["Chat", "அரட்டை"],
  "Zur Startseite": ["Back to the home page", "முகப்புப் பக்கத்திற்கு"],
  "Abmelden": ["Sign out", "வெளியேறு"],
  "Sprache": ["Language", "மொழி"],
});

// ——— Auswahllisten (Texte aus lib/onboarding.ts) ———
register({
  "Friends-Community": ["Friends community", "நட்பு சமூகம்"],
  "Business-Community": ["Business community", "வணிக சமூகம்"],
  "Männlich": ["Male", "ஆண்"],
  "Weiblich": ["Female", "பெண்"],
  "Nicht-binär / divers": ["Non-binary / diverse", "பைனரி அல்லாதவர் / பன்முகம்"],
  "Möchte ich nicht angeben": ["Prefer not to say", "குறிப்பிட விரும்பவில்லை"],
  "Keine Angabe": ["Not specified", "குறிப்பிடப்படவில்லை"],
  "Männliche Freundschaften": ["Male friendships", "ஆண் நட்புகள்"],
  "Weibliche Freundschaften": ["Female friendships", "பெண் நட்புகள்"],
  "Egal, mir ist es wichtig, dass es passt": ["Doesn't matter, what counts is that it fits", "முக்கியமில்லை, பொருத்தம்தான் முக்கியம்"],
  "Gemischte Gruppe": ["Mixed group", "கலப்புக் குழு"],
  "Nur Männer": ["Men only", "ஆண்கள் மட்டும்"],
  "Nur Frauen": ["Women only", "பெண்கள் மட்டும்"],
  "Egal, Hauptsache Match": ["Doesn't matter, as long as it's a match", "முக்கியமில்லை, பொருத்தம் இருந்தால் போதும்"],
  "Duo (2er Gruppe)": ["Duo (group of 2)", "இருவர் (2 பேர் குழு)"],
  "Crew (4er Gruppe)": ["Crew (group of 4)", "குழு (4 பேர்)"],
  "Squad (8er Gruppe)": ["Squad (group of 8)", "பெரிய குழு (8 பேர்)"],
  "Egal": ["Any", "எதுவாயினும்"],
  "Nur online schreiben": ["Online chatting only", "ஆன்லைனில் மட்டும் பேசுதல்"],
  "Auch gemeinsame Aktivitäten und Hobbys vor Ort": ["Also shared activities and hobbies in person", "நேரில் இணைந்து செயல்பாடுகளும் பொழுதுபோக்குகளும்"],
  "10 Minuten": ["10 minutes", "10 நிமிடங்கள்"],
  "20 Minuten": ["20 minutes", "20 நிமிடங்கள்"],
  "45 Minuten": ["45 minutes", "45 நிமிடங்கள்"],
  "1 Stunde": ["1 hour", "1 மணி நேரம்"],
  "2 Stunden": ["2 hours", "2 மணி நேரம்"],
  "Seltener als 1× im Monat": ["Less than once a month", "மாதம் ஒருமுறைக்கும் குறைவாக"],
  "1–2× im Monat": ["1–2 times a month", "மாதம் 1–2 முறை"],
  "1–2× pro Woche": ["1–2 times a week", "வாரம் 1–2 முறை"],
  "3× pro Woche oder öfter": ["3 times a week or more", "வாரம் 3 முறை அல்லது அதற்கு மேல்"],
  "Tamil": ["Tamil", "தமிழ்"],
  "Deutsch": ["German", "ஜெர்மன்"],
  "Englisch": ["English", "ஆங்கிலம்"],
  "Französisch": ["French", "பிரெஞ்சு"],
  "Mix aus allem": ["A mix of everything", "அனைத்தும் கலந்து"],
  "Schule": ["School", "பள்ளி"],
  "Studium": ["University", "கல்லூரிப் படிப்பு"],
  "Ausbildung": ["Apprenticeship", "தொழிற்பயிற்சி"],
  "Beruf": ["Work", "வேலை"],
  "Sonstiges": ["Other", "மற்றவை"],
  "Gym": ["Gym", "உடற்பயிற்சி நிலையம்"],
  "Gaming": ["Gaming", "கேமிங்"],
  "Kultur": ["Culture", "கலாச்சாரம்"],
  "Deep Talks": ["Deep talks", "ஆழமான உரையாடல்கள்"],
  "Musik": ["Music", "இசை"],
  "Tanzen": ["Dancing", "நடனம்"],
  "Essen & Kochen": ["Food & cooking", "உணவு & சமையல்"],
  "Reisen": ["Travel", "பயணம்"],
  "Sport": ["Sports", "விளையாட்டு"],
  "Kreatives": ["Creative things", "படைப்பாற்றல்"],
  "Karriere & Business": ["Career & business", "தொழில் & வணிகம்"],
  "Filme & Serien": ["Movies & series", "திரைப்படங்கள் & தொடர்கள்"],
  "Entspannt": ["Relaxed", "நிதானமானவர்"],
  "Zielorientiert": ["Goal-oriented", "இலக்கை நோக்கியவர்"],
  "Kreativ": ["Creative", "படைப்பாற்றல் மிக்கவர்"],
  "Abenteuerlustig": ["Adventurous", "சாகசப் பிரியர்"],
  "Humorvoll": ["Humorous", "நகைச்சுவை உணர்வுள்ளவர்"],
  "Tiefgründig": ["Thoughtful", "ஆழ்ந்து சிந்திப்பவர்"],
  "Spontan": ["Spontaneous", "தன்னிச்சையானவர்"],
  "Bodenständig": ["Down to earth", "எளிமையானவர்"],
  "Öffentlich": ["Public", "பொது"],
  "Nur Business": ["Business only", "வணிகர்கள் மட்டும்"],
  "Privat": ["Private", "தனிப்பட்டது"],
  "Online": ["Online", "ஆன்லைன்"],
  "Warteliste (noch kein Hub in der Nähe)": ["Waiting list (no hub nearby yet)", "காத்திருப்புப் பட்டியல் (அருகில் இன்னும் மையம் இல்லை)"],
  "Berlin & Ost": ["Berlin & East", "பெர்லின் & கிழக்கு"],
  "Hamburg & Nord": ["Hamburg & North", "ஹாம்பர்க் & வடக்கு"],
  "Bayern": ["Bavaria", "பவேரியா"],
  "Schweiz": ["Switzerland", "சுவிட்சர்லாந்து"],
  "Österreich": ["Austria", "ஆஸ்திரியா"],
  "Tech & Software": ["Tech & software", "தொழில்நுட்பம் & மென்பொருள்"],
  "Finanzen & Investment": ["Finance & investment", "நிதி & முதலீடு"],
  "Gesundheit & Medizin": ["Health & medicine", "சுகாதாரம் & மருத்துவம்"],
  "Handel & E-Commerce": ["Retail & e-commerce", "வர்த்தகம் & இ-காமர்ஸ்"],
  "Medien & Kreatives": ["Media & creative", "ஊடகம் & படைப்பாற்றல்"],
  "Bildung & Forschung": ["Education & research", "கல்வி & ஆராய்ச்சி"],
  "Gastronomie & Food": ["Hospitality & food", "உணவகத் துறை & உணவு"],
  "Immobilien & Bau": ["Real estate & construction", "ரியல் எஸ்டேட் & கட்டுமானம்"],
  "Beratung & Services": ["Consulting & services", "ஆலோசனை & சேவைகள்"],
  "Industrie & Handwerk": ["Industry & crafts", "தொழிற்துறை & கைவினை"],
  "Co-Founder finden": ["Find a co-founder", "இணை நிறுவனரைக் கண்டறிதல்"],
  "Investoren-Austausch": ["Exchange with investors", "முதலீட்டாளர்களுடன் கலந்துரையாடல்"],
  "Projekt-Kollaboration": ["Project collaboration", "திட்டக் கூட்டுப்பணி"],
  "Mentoring": ["Mentoring", "வழிகாட்டுதல்"],
  "Kunden & Partner finden": ["Find customers & partners", "வாடிக்கையாளர்கள் & கூட்டாளிகளைக் கண்டறிதல்"],
  "Netzwerk aufbauen": ["Build a network", "தொடர்பு வலையமைப்பை உருவாக்குதல்"],
});

// ——— Steckbrief-Beschriftungen ———
register({
  "Geschlecht": ["Gender", "பாலினம்"],
  "Verbinden mit": ["Connect with", "இணைக்க விரும்புவது"],
  "Alter": ["Age", "வயது"],
  "Gesuchtes Alter": ["Preferred age", "விரும்பும் வயது"],
  "Gruppengröße": ["Group size", "குழு அளவு"],
  "Art der Freundschaft": ["Type of friendship", "நட்பின் வகை"],
  "Max. Entfernung (Auto)": ["Max. distance (car)", "அதிகபட்ச தூரம் (கார்)"],
  "Sprachen": ["Languages", "மொழிகள்"],
  "Lebensphase": ["Life stage", "வாழ்க்கை நிலை"],
  "Hub": ["Hub", "மையம்"],
  "Hubs": ["Hubs", "மையங்கள்"],
  "Stadt": ["City", "நகரம்"],
  "Interessen": ["Interests", "ஆர்வங்கள்"],
  "Vibe": ["Vibe", "இயல்பு"],
  "Grund für zwei Hubs": ["Reason for two hubs", "இரண்டு மையங்களுக்கான காரணம்"],
  "Maximale Treffhäufigkeit": ["Max. meeting frequency", "அதிகபட்ச சந்திப்பு அடிக்கடி"],
  "Business": ["Business", "வணிகம்"],
  "Business-Ziele": ["Business goals", "வணிக இலக்குகள்"],
  "Expertise": ["Expertise", "நிபுணத்துவம்"],
});

// ——— Profil (Hauptseite) ———
register({
  "DSpora Profil": ["DSpora profile", "DSpora சுயவிவரம்"],
  "Hey {name}": ["Hey {name}", "வணக்கம் {name}"],
  "Willkommen": ["Welcome", "வரவேற்கிறோம்"],
  "Admin Dashboard": ["Admin dashboard", "நிர்வாகப் பலகை"],
  "Deine Matches warten": ["Your matches are waiting", "உங்கள் இணைப்புகள் காத்திருக்கின்றன"],
  "Dein Hub bereitet Matches vor": ["Your hub is preparing matches", "உங்கள் மையம் இணைப்புகளைத் தயார் செய்கிறது"],
  "Wir prüfen die Anmeldungen und öffnen deinen Hub, sobald genug passende Leute dabei sind. Jedes Match schauen wir uns vorher an. Du musst nichts weiter tun.": [
    "We review the sign-ups and open your hub as soon as enough suitable people have joined. We look at every match beforehand. You don't have to do anything else.",
    "பதிவுகளை நாங்கள் பரிசீலித்து, போதுமான பொருத்தமானவர்கள் சேர்ந்தவுடன் உங்கள் மையத்தைத் திறக்கிறோம். ஒவ்வொரு இணைப்பையும் முன்கூட்டியே பார்க்கிறோம். நீங்கள் வேறு எதுவும் செய்ய வேண்டியதில்லை.",
  ],
  "{n} aktiver Chat (höchstens 4)": ["{n} active chat (max. 4)", "{n} செயலில் உள்ள அரட்டை (அதிகபட்சம் 4)"],
  "{n} aktive Chats (höchstens 4)": ["{n} active chats (max. 4)", "{n} செயலில் உள்ள அரட்டைகள் (அதிகபட்சம் 4)"],
  "Dein Hub bereitet passende Verbindungen vor": ["Your hub is preparing suitable connections", "உங்கள் மையம் பொருத்தமான இணைப்புகளைத் தயார் செய்கிறது"],
  "Dein Hub bereitet passende Business-Verbindungen vor": ["Your hub is preparing suitable business connections", "உங்கள் மையம் பொருத்தமான வணிக இணைப்புகளைத் தயார் செய்கிறது"],
  "Pausiert. Wechsle oben auf „Friends-Community“, um sie zu aktivieren.": ["Paused. Switch to “Friends community” above to activate it.", "இடைநிறுத்தப்பட்டது. செயல்படுத்த மேலே “நட்பு சமூகம்” என்பதற்கு மாறவும்."],
  "Nicht aktiv. Wechsle oben auf „Business-Community“, um sie zu aktivieren.": ["Not active. Switch to “Business community” above to activate it.", "செயலில் இல்லை. செயல்படுத்த மேலே “வணிக சமூகம்” என்பதற்கு மாறவும்."],
  "Profil und Antworten sind gespeichert": ["Profile and answers are saved", "சுயவிவரமும் பதில்களும் சேமிக்கப்பட்டன"],
  "{n} Anmeldung im Hub {hub}": ["{n} sign-up in the {hub} hub", "{hub} மையத்தில் {n} பதிவு"],
  "{n} Anmeldungen im Hub {hub}": ["{n} sign-ups in the {hub} hub", "{hub} மையத்தில் {n} பதிவுகள்"],
  "Matching: in Vorbereitung": ["Matching: in preparation", "இணைப்பு: தயாராகிறது"],
  "Dein Profil": ["Your profile", "உங்கள் சுயவிவரம்"],
  "Modus": ["Mode", "முறை"],
  "Für den Business-Modus brauchen wir noch ein paar Angaben und dein Light-CV.": ["For business mode we still need a few details and your light CV.", "வணிக முறைக்கு இன்னும் சில விவரங்களும் உங்கள் சுருக்கமான சுயவிவரமும் தேவை."],
  "Business-Profil einrichten": ["Set up business profile", "வணிகச் சுயவிவரத்தை அமைக்கவும்"],
  "Art der Freundschaft und Wohnort": ["Type of friendship and place of residence", "நட்பின் வகை மற்றும் வசிப்பிடம்"],
  "Ort ändern": ["Change place", "இடத்தை மாற்று"],
  "Dein Wohnort": ["Your place of residence", "உங்கள் வசிப்பிடம்"],
  "Bitte gib deinen Wohnort an.": ["Please enter your place of residence.", "உங்கள் வசிப்பிடத்தை உள்ளிடவும்."],
  "Diesen Ort konnte ich nicht zuordnen. Bitte gib die nächstgrößere Stadt an.": ["I couldn't match this place. Please enter the nearest larger city.", "இந்த இடத்தைப் பொருத்த முடியவில்லை. அருகிலுள்ள பெரிய நகரத்தை உள்ளிடவும்."],
  "„{name}“ gehört zum Hub {hub}.": ["“{name}” belongs to the {hub} hub.", "“{name}” {hub} மையத்தைச் சேர்ந்தது."],
  "Wie weit darf jemand maximal entfernt wohnen? (Fahrzeit mit dem Auto)": ["How far away may someone live at most? (driving time by car)", "ஒருவர் அதிகபட்சம் எவ்வளவு தூரத்தில் வசிக்கலாம்? (காரில் பயண நேரம்)"],
  "Maximale Entfernung": ["Maximum distance", "அதிகபட்ச தூரம்"],
  "Wie oft würdest du dich realistisch treffen?": ["How often would you realistically meet?", "நடைமுறையில் எவ்வளவு அடிக்கடி சந்திப்பீர்கள்?"],
  "Treffhäufigkeit": ["Meeting frequency", "சந்திப்பு அடிக்கடி"],
  "Alter und gesuchte Altersspanne": ["Age and preferred age range", "வயது மற்றும் விரும்பும் வயது வரம்பு"],
  "Dein Alter": ["Your age", "உங்கள் வயது"],
  "Gesucht von": ["Looking for", "தேடும் வயது"],
  "Gesucht ab": ["Looking from age", "இந்த வயதிலிருந்து"],
  "Gesucht bis": ["Looking up to age", "இந்த வயது வரை"],
  "bis": ["to", "–"],
  "Bitte gib Zahlen zwischen {min} und {max} an.": ["Please enter numbers between {min} and {max}.", "{min} மற்றும் {max} இடையே எண்களை உள்ளிடவும்."],
  "Altersspanne: „von“ darf nicht größer sein als „bis“.": ["Age range: “from” must not be greater than “to”.", "வயது வரம்பு: தொடக்க வயது இறுதி வயதை விடப் பெரிதாக இருக்கக் கூடாது."],
  "Eine andere Sprache? Eigene hinzufügen": ["Another language? Add your own", "வேறு மொழியா? உங்களுடையதைச் சேர்க்கவும்"],
  "Es zählt, wie du dich selbst identifizierst.": ["What counts is how you identify yourself.", "நீங்கள் உங்களை எவ்வாறு அடையாளப்படுத்துகிறீர்கள் என்பதே முக்கியம்."],
  "Mit wem möchtest du dich verbinden?": ["Who would you like to connect with?", "யாருடன் இணைய விரும்புகிறீர்கள்?"],
  "Gewünschte Gruppengröße": ["Desired group size", "விரும்பும் குழு அளவு"],
  "Eigenes hinzufügen": ["Add your own", "உங்களுடையதைச் சேர்க்கவும்"],
  "Eigenen Vibe hinzufügen": ["Add your own vibe", "உங்கள் இயல்பைச் சேர்க்கவும்"],
  "Für den Business-Modus brauchst du ein Profil mit Namen. Lege es zuerst an.": ["For business mode you need a profile with a name. Please create it first.", "வணிக முறைக்குப் பெயருடன் சுயவிவரம் தேவை. முதலில் அதை உருவாக்கவும்."],
  "Deine Chats": ["Your chats", "உங்கள் அரட்டைகள்"],
  "Du kannst höchstens vier Chats gleichzeitig führen, damit jedes Gespräch echten Fokus bekommt. Verlässt du einen Chat, wird ein Platz für ein neues Match frei.": [
    "You can have at most four chats at the same time so that every conversation gets real focus. If you leave a chat, a spot opens up for a new match.",
    "ஒவ்வொரு உரையாடலுக்கும் உண்மையான கவனம் கிடைக்க, ஒரே நேரத்தில் அதிகபட்சம் நான்கு அரட்டைகளை மட்டுமே நடத்தலாம். ஒரு அரட்டையை விட்டு வெளியேறினால், புதிய இணைப்புக்கு இடம் கிடைக்கும்.",
  ],
  "{n} von 4": ["{n} of 4", "4 இல் {n}"],
  "Zu den Chats": ["Go to chats", "அரட்டைகளுக்குச் செல்"],
  "{n} neu": ["{n} new", "{n} புதியவை"],
  "Dein Steckbrief": ["Your profile summary", "உங்கள் விவரச்சுருக்கம்"],
  "Das weiß DSpora aktuell über dich. So kann die KI dich immer auf dem neuesten Stand ansprechen. Erzähl ihr jederzeit Neues, oder entferne Angaben, die nicht mehr stimmen. Gefragt wird sie auch im Gespräch („Zeig mir meinen Steckbrief“).": [
    "This is what DSpora currently knows about you. That way the AI can always talk to you with up-to-date information. Tell it something new at any time, or remove details that are no longer true. You can also ask for it in the conversation (“Show me my profile summary”).",
    "DSpora தற்போது உங்களைப் பற்றி அறிந்தவை இவை. இதன் மூலம் AI எப்போதும் சமீபத்திய தகவலுடன் உங்களுடன் பேச முடியும். எப்போது வேண்டுமானாலும் புதியதைச் சொல்லுங்கள், அல்லது இனி சரியில்லாத விவரங்களை அகற்றுங்கள். உரையாடலிலும் இதைக் கேட்கலாம் (“என் விவரச்சுருக்கத்தைக் காட்டு”).",
  ],
  "Das hast du erzählt": ["What you told us", "நீங்கள் கூறியவை"],
  "Noch nichts. Im Gespräch lernt die KI dich besser kennen.": ["Nothing yet. In the conversation the AI gets to know you better.", "இன்னும் எதுவும் இல்லை. உரையாடலில் AI உங்களை நன்றாக அறிந்துகொள்கிறது."],
  "Diese Angabe entfernen": ["Remove this entry", "இந்த விவரத்தை அகற்று"],
  "Mit der KI sprechen": ["Talk to the AI", "AI உடன் பேசுங்கள்"],
  "Deine Ideen für DSpora": ["Your ideas for DSpora", "DSpora க்கான உங்கள் யோசனைகள்"],
  "Was wünschst du dir? Welche Features sollten wir unbedingt einbauen? Wir lesen jede Idee.": ["What do you wish for? Which features should we definitely build? We read every idea.", "நீங்கள் என்ன விரும்புகிறீர்கள்? எந்த அம்சங்களை நாங்கள் கண்டிப்பாகச் சேர்க்க வேண்டும்? ஒவ்வொரு யோசனையையும் படிக்கிறோம்."],
  "Meine Idee …": ["My idea …", "என் யோசனை …"],
  "Idee für DSpora": ["Idea for DSpora", "DSpora க்கான யோசனை"],
  "Idee senden": ["Send idea", "யோசனையை அனுப்பு"],
  "Vorschau: nichts wurde gespeichert.": ["Preview: nothing was saved.", "முன்னோட்டம்: எதுவும் சேமிக்கப்படவில்லை."],
  "Danke! Deine Idee ist angekommen.": ["Thank you! Your idea has arrived.", "நன்றி! உங்கள் யோசனை கிடைத்தது."],
  "Schneller anmelden": ["Sign in faster", "விரைவாக உள்நுழைக"],
  "Mit einem Passkey meldest du dich per Face ID, Touch ID oder Schlüsselbund an. Ein Passwort gibt es bei DSpora nicht.": [
    "With a passkey you sign in using Face ID, Touch ID or your keychain. DSpora has no passwords.",
    "Passkey மூலம் Face ID, Touch ID அல்லது கீசெயின் பயன்படுத்தி உள்நுழைகிறீர்கள். DSpora வில் கடவுச்சொல் இல்லை.",
  ],
  "Passkey hinzufügen": ["Add a passkey", "Passkey சேர்"],
  "Der Passkey konnte nicht angelegt werden.": ["The passkey could not be created.", "Passkey ஐ உருவாக்க முடியவில்லை."],
  "Passkey hinzugefügt. Ab jetzt kannst du dich mit Face ID oder Touch ID anmelden.": ["Passkey added. From now on you can sign in with Face ID or Touch ID.", "Passkey சேர்க்கப்பட்டது. இனி Face ID அல்லது Touch ID மூலம் உள்நுழையலாம்."],
  "Benachrichtigungen": ["Notifications", "அறிவிப்புகள்"],
  "E-Mail, wenn ein neuer Chat auf dich wartet": ["Email when a new chat is waiting for you", "புதிய அரட்டை காத்திருக்கும்போது மின்னஞ்சல்"],
  "Die Mail enthält keine Angaben zu deinem Match, nur einen Link in dein Profil.": ["The email contains no details about your match, only a link to your profile.", "மின்னஞ்சலில் உங்கள் இணைப்பைப் பற்றிய விவரங்கள் இல்லை, உங்கள் சுயவிவரத்திற்கான இணைப்பு மட்டுமே."],
  "Konto löschen": ["Delete account", "கணக்கை நீக்கு"],
  "Dein Konto wird sofort gesperrt. Deine Daten bleiben noch 30 Tage gespeichert, falls du es dir anders überlegst oder Hilfe brauchst. Danach werden sie endgültig gelöscht.": [
    "Your account is blocked immediately. Your data stays stored for 30 more days in case you change your mind or need help. After that it is deleted permanently.",
    "உங்கள் கணக்கு உடனடியாக முடக்கப்படும். நீங்கள் மனம் மாறினால் அல்லது உதவி தேவைப்பட்டால் உங்கள் தரவு 30 நாட்கள் சேமிக்கப்படும். அதன் பிறகு அவை நிரந்தரமாக நீக்கப்படும்.",
  ],
  "Konto löschen …": ["Delete account …", "கணக்கை நீக்கு …"],
  "Möchtest du dein Konto wirklich löschen?": ["Do you really want to delete your account?", "உங்கள் கணக்கை உண்மையிலேயே நீக்க விரும்புகிறீர்களா?"],
  "Ja, Konto löschen": ["Yes, delete account", "ஆம், கணக்கை நீக்கு"],
  "Das Konto konnte nicht gelöscht werden. Bitte versuch es noch einmal.": ["The account could not be deleted. Please try again.", "கணக்கை நீக்க முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்."],
  "Chat erneut durchspielen": ["Go through the chat again", "அரட்டையை மீண்டும் நடத்து"],
});

// ——— Auswahlfelder ———
register({
  "Wähle mindestens eins": ["Choose at least one", "குறைந்தது ஒன்றைத் தேர்ந்தெடுக்கவும்"],
  "Optional": ["Optional", "விருப்பத்திற்குரியது"],
  "{n} gewählt": ["{n} selected", "{n} தேர்ந்தெடுக்கப்பட்டன"],
  "2 bis 30 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["2 to 30 characters, only letters, numbers and simple characters.", "2 முதல் 30 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
});

// ——— Business-Angaben ———
register({
  "Business & Light-CV": ["Business & light CV", "வணிகம் & சுருக்கச் சுயவிவரம்"],
  "Bitte gib deine Rolle an.": ["Please enter your role.", "உங்கள் பங்கை உள்ளிடவும்."],
  "Bitte wähle eine Branche.": ["Please choose an industry.", "ஒரு துறையைத் தேர்ந்தெடுக்கவும்."],
  "Bitte wähle mindestens ein Ziel.": ["Please choose at least one goal.", "குறைந்தது ஒரு இலக்கைத் தேர்ந்தெடுக்கவும்."],
  "Branche / Sektor": ["Industry / sector", "துறை / பிரிவு"],
  "Andere Branche? Eigene Angabe": ["Another industry? Enter your own", "வேறு துறையா? உங்களுடையதை உள்ளிடவும்"],
  "Aktuelle Rolle": ["Current role", "தற்போதைய பங்கு"],
  "z. B. Gründerin, Product Manager": ["e.g. founder, product manager", "எ.கா. நிறுவனர், தயாரிப்பு மேலாளர்"],
  "Hauptziel": ["Main goal", "முக்கிய இலக்கு"],
  "bis zu 3": ["up to 3", "3 வரை"],
  "Ein anderes Ziel?": ["Another goal?", "வேறு இலக்கா?"],
  "Branche:": ["Industry:", "துறை:"],
  "· Rolle:": ["· Role:", "· பங்கு:"],
  "Expertise:": ["Expertise:", "நிபுணத்துவம்:"],
  "Expertise": ["Expertise", "நிபுணத்துவம்"],
  "Worin bist du richtig gut? z. B. Produktstrategie, Fullstack, Vertrieb": ["What are you really good at? e.g. product strategy, full-stack, sales", "நீங்கள் எதில் மிகவும் திறமையானவர்? எ.கா. தயாரிப்பு உத்தி, ஃபுல்ஸ்டாக், விற்பனை"],
  "Deine Top-3-Erfolge": ["Your top 3 achievements", "உங்கள் முதல் 3 சாதனைகள்"],
  "kurz, optional": ["short, optional", "சுருக்கமாக, விருப்பத்திற்குரியது"],
  "Links": ["Links", "இணைப்புகள்"],
  "Portfolio, GitHub, Website, optional": ["Portfolio, GitHub, website, optional", "போர்ட்ஃபோலியோ, GitHub, வலைத்தளம், விருப்பத்திற்குரியது"],
});

// ——— Anmeldung ———
register({
  "Willkommen zurück": ["Welcome back", "மீண்டும் வருக"],
  "Ohne Passwort: Wir schicken dir einen Link oder du nutzt deinen Passkey.": ["No password: we send you a link, or you use your passkey.", "கடவுச்சொல் இல்லை: நாங்கள் இணைப்பை அனுப்புகிறோம் அல்லது உங்கள் Passkey ஐப் பயன்படுத்தலாம்."],
  "Die Anmeldung wird gerade eingerichtet und ist bald verfügbar.": ["Sign-in is being set up and will be available soon.", "உள்நுழைவு அமைக்கப்படுகிறது, விரைவில் கிடைக்கும்."],
  "Check dein Postfach: Wir haben dir einen Link an {email} geschickt.": ["Check your inbox: we sent a link to {email}.", "உங்கள் இன்பாக்ஸைப் பாருங்கள்: {email} முகவரிக்கு இணைப்பை அனுப்பியுள்ளோம்."],
  "Schau auch im Spam-Ordner nach.": ["Also check your spam folder.", "ஸ்பேம் கோப்புறையையும் பாருங்கள்."],
  "E-Mail-Adresse": ["Email address", "மின்னஞ்சல் முகவரி"],
  "oder": ["or", "அல்லது"],
  "deine@mail.com": ["your@mail.com", "உங்கள்@mail.com"],
  "Bitte gib eine gültige E-Mail-Adresse ein.": ["Please enter a valid email address.", "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்."],
  "Das hat leider nicht geklappt. Bitte versuch es noch einmal.": ["Unfortunately that didn't work. Please try again.", "துரதிர்ஷ்டவசமாக அது வெற்றிபெறவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்."],
  "Mit dem Passkey hat es nicht geklappt. Du kannst dir stattdessen einen Link per E-Mail schicken lassen.": ["The passkey didn't work. You can have a link sent by email instead.", "Passkey வேலை செய்யவில்லை. அதற்குப் பதிலாக மின்னஞ்சலில் இணைப்பைப் பெறலாம்."],
  "Erneut senden in {n} s": ["Send again in {n} s", "{n} வினாடியில் மீண்டும் அனுப்பலாம்"],
  "Link erneut senden": ["Send link again", "இணைப்பை மீண்டும் அனுப்பு"],
  "Link per E-Mail senden": ["Send link by email", "இணைப்பை மின்னஞ்சலில் அனுப்பு"],
  "Warte auf dein Gerät …": ["Waiting for your device …", "உங்கள் சாதனத்திற்காகக் காத்திருக்கிறது …"],
  "Mit Passkey anmelden": ["Sign in with passkey", "Passkey மூலம் உள்நுழை"],
});

// ——— Chat-Übersicht und Chat-Fenster (ohne die Nachrichten selbst) ———
register({
  "← Profil": ["← Profile", "← சுயவிவரம்"],
  "← Chats": ["← Chats", "← அரட்டைகள்"],
  "Du kannst höchstens vier Chats gleichzeitig führen": ["You can have at most four chats at the same time", "ஒரே நேரத்தில் அதிகபட்சம் நான்கு அரட்டைகள் மட்டுமே"],
  "{n} von {max} Plätzen belegt": ["{n} of {max} spots taken", "{max} இடங்களில் {n} நிரம்பியுள்ளன"],
  "Du kannst höchstens {max} Chats gleichzeitig führen, damit jedes Gespräch Raum bekommt. Verlässt du einen Chat, wird ein Platz für ein neues Match frei.": [
    "You can have at most {max} chats at the same time so that every conversation gets room. If you leave a chat, a spot opens up for a new match.",
    "ஒவ்வொரு உரையாடலுக்கும் இடம் கிடைக்க, ஒரே நேரத்தில் அதிகபட்சம் {max} அரட்டைகளை மட்டுமே நடத்தலாம். ஒரு அரட்டையை விட்டு வெளியேறினால், புதிய இணைப்புக்கு இடம் கிடைக்கும்.",
  ],
  "Noch keine Chats": ["No chats yet", "இன்னும் அரட்டைகள் இல்லை"],
  "Sobald dein Hub öffnet und wir passende Menschen für dich gefunden haben, startet hier dein erster Chat, mit einem Eisbrecher, der zu euren Gemeinsamkeiten passt.": [
    "As soon as your hub opens and we have found suitable people for you, your first chat starts here, with an icebreaker that fits what you have in common.",
    "உங்கள் மையம் திறந்து, உங்களுக்குப் பொருத்தமானவர்களைக் கண்டறிந்தவுடன், உங்கள் பொதுவான விஷயங்களுக்குப் பொருந்தும் ஒரு தொடக்கக் கேள்வியுடன் உங்கள் முதல் அரட்டை இங்கே தொடங்கும்.",
  ],
  "Die Chats konnten nicht geladen werden.": ["The chats could not be loaded.", "அரட்டைகளை ஏற்ற முடியவில்லை."],
  "Allein im Chat": ["Alone in the chat", "அரட்டையில் தனியாக"],
  "Duo": ["Duo", "இருவர்"],
  "Gruppe · {n} Personen": ["Group · {n} people", "குழு · {n} பேர்"],
  " · Business": [" · Business", " · வணிகம்"],
  " · beendet": [" · ended", " · முடிந்தது"],
  "Chat wird geladen …": ["Loading chat …", "அரட்டை ஏற்றப்படுகிறது …"],
  "Melden": ["Report", "புகாரளி"],
  "Profil ansehen": ["View profile", "சுயவிவரத்தைப் பார்"],
  "Chat entfernen": ["Remove chat", "அரட்டையை அகற்று"],
  "Verlassen": ["Leave", "வெளியேறு"],
  "Chat endgültig entfernen?": ["Remove chat permanently?", "அரட்டையை நிரந்தரமாக அகற்றவா?"],
  "Wirklich verlassen? Der Platz wird frei.": ["Really leave? Your spot will be freed.", "உண்மையிலேயே வெளியேறவா? உங்கள் இடம் விடுவிக்கப்படும்."],
  "Was ist passiert?": ["What happened?", "என்ன நடந்தது?"],
  "Wir lesen keine Nachrichten mit, ein kurzer Hinweis hilft uns. Du verlässt danach den Chat und wirst mit dieser Person nicht noch einmal zusammengebracht.": [
    "We don't read any messages; a short note helps us. You will then leave the chat and will not be matched with this person again.",
    "நாங்கள் செய்திகளைப் படிப்பதில்லை; ஒரு சிறு குறிப்பு எங்களுக்கு உதவும். அதன் பிறகு நீங்கள் அரட்டையை விட்டு வெளியேறுவீர்கள், இந்த நபருடன் மீண்டும் இணைக்கப்பட மாட்டீர்கள்.",
  ],
  "Unangenehm oder respektlos": ["Unpleasant or disrespectful", "அசௌகரியமான அல்லது மரியாதையற்ற"],
  "Belästigung": ["Harassment", "தொல்லை"],
  "Spam oder Werbung": ["Spam or advertising", "ஸ்பேம் அல்லது விளம்பரம்"],
  "Fake-Profil": ["Fake profile", "போலி சுயவிவரம்"],
  "Etwas anderes": ["Something else", "வேறு ஏதாவது"],
  "Kurzer Hinweis (optional)": ["Short note (optional)", "சிறு குறிப்பு (விருப்பத்திற்குரியது)"],
  "Kurzer Hinweis zur Meldung": ["Short note about the report", "புகார் பற்றிய சிறு குறிப்பு"],
  "Melden und Chat verlassen": ["Report and leave chat", "புகாரளித்து அரட்டையை விட்டு வெளியேறு"],
  "Warum ihr gematcht wurdet": ["Why you were matched", "நீங்கள் ஏன் இணைக்கப்பட்டீர்கள்"],
  "Match-Steckbrief": ["Match summary", "இணைப்பு விவரச்சுருக்கம்"],
  "Dieser Steckbrief wird gelöscht, sobald der Chat endet.": ["This summary is deleted as soon as the chat ends.", "அரட்டை முடிந்தவுடன் இந்த விவரச்சுருக்கம் நீக்கப்படும்."],
  "Wie fühlt sich dieser Chat an?": ["How does this chat feel?", "இந்த அரட்டை எப்படி உணர்கிறது?"],
  "Gut": ["Good", "நன்று"],
  "Geht so": ["So-so", "பரவாயில்லை"],
  "Nicht gut": ["Not good", "நன்றாக இல்லை"],
  "Dieser Chat ist beendet. Du kannst ihn oben entfernen, dann ist er endgültig gelöscht.": ["This chat has ended. You can remove it above, then it is deleted permanently.", "இந்த அரட்டை முடிந்துவிட்டது. மேலே அதை அகற்றலாம், பிறகு அது நிரந்தரமாக நீக்கப்படும்."],
  "Spark denkt nach …": ["Spark is thinking …", "Spark சிந்திக்கிறது …"],
  "Eisbrecher": ["Icebreaker", "தொடக்கக் கேள்வி"],
  "Schreib eine Nachricht …": ["Write a message …", "ஒரு செய்தியை எழுதுங்கள் …"],
  "Nachricht": ["Message", "செய்தி"],
  "Senden": ["Send", "அனுப்பு"],
  "Senden hat nicht geklappt.": ["Sending didn't work.", "அனுப்ப முடியவில்லை."],
  "Der Impuls konnte nicht geholt werden.": ["The icebreaker could not be fetched.", "தொடக்கக் கேள்வியைப் பெற முடியவில்லை."],
  "Verlassen hat nicht geklappt.": ["Leaving didn't work.", "வெளியேற முடியவில்லை."],
  "Die Meldung hat nicht geklappt.": ["The report didn't work.", "புகார் அளிக்க முடியவில்லை."],
});

// ——— Profilseite ———
register({
  "Deine Profilseite": ["Your profile page", "உங்கள் சுயவிவரப் பக்கம்"],
  "So sehen dich andere. Beiträge zeigst du mit Bildern, die du wischen kannst.": ["This is how others see you. You show posts with images that can be swiped.", "மற்றவர்கள் உங்களை இப்படிப் பார்க்கிறார்கள். வருடிப் பார்க்கக்கூடிய படங்களுடன் பதிவுகளைக் காட்டுகிறீர்கள்."],
  "Ansehen": ["View", "பார்"],
  "Sichtbarkeit der Profilseite": ["Visibility of the profile page", "சுயவிவரப் பக்கத்தின் தெரிவுநிலை"],
  "Alle angemeldeten Mitglieder sehen Name, Alter, Text, Hobbys und Beiträge.": ["All signed-in members see name, age, text, hobbies and posts.", "உள்நுழைந்த அனைத்து உறுப்பினர்களும் பெயர், வயது, உரை, பொழுதுபோக்குகள் மற்றும் பதிவுகளைப் பார்க்கலாம்."],
  "Business-Mitglieder sehen alles, alle anderen nur Profilbild und Spitzname.": ["Business members see everything, everyone else only the profile picture and nickname.", "வணிக உறுப்பினர்கள் அனைத்தையும் பார்ப்பார்கள், மற்றவர்கள் சுயவிவரப் படம் மற்றும் புனைப்பெயரை மட்டும் பார்ப்பார்கள்."],
  "Nur Profilbild und Spitzname sind sichtbar, und nur für Leute, mit denen du in einem Chat bist.": ["Only the profile picture and nickname are visible, and only to people you are in a chat with.", "சுயவிவரப் படமும் புனைப்பெயரும் மட்டுமே தெரியும், நீங்கள் அரட்டையில் இருப்பவர்களுக்கு மட்டுமே."],
  "Dein Profilbild": ["Your profile picture", "உங்கள் சுயவிவரப் படம்"],
  "Profilbild auswählen": ["Choose profile picture", "சுயவிவரப் படத்தைத் தேர்ந்தெடு"],
  "Lade hoch …": ["Uploading …", "பதிவேற்றுகிறது …"],
  "Bild ändern": ["Change picture", "படத்தை மாற்று"],
  "Profilbild hinzufügen": ["Add profile picture", "சுயவிவரப் படத்தைச் சேர்"],
  "Spitzname oder Künstlername": ["Nickname or stage name", "புனைப்பெயர் அல்லது கலைப்பெயர்"],
  "Vorname (optional)": ["First name (optional)", "முதல் பெயர் (விருப்பத்திற்குரியது)"],
  "Nachname (optional)": ["Last name (optional)", "குடும்பப் பெயர் (விருப்பத்திற்குரியது)"],
  "Name und Nachname siehst nur du, solange dein Profil privat ist.": ["Only you can see first and last name as long as your profile is private.", "உங்கள் சுயவிவரம் தனிப்பட்டதாக இருக்கும் வரை பெயரையும் குடும்பப் பெயரையும் நீங்கள் மட்டுமே பார்க்கலாம்."],
  "Über mich": ["About me", "என்னைப் பற்றி"],
  "Ein paar Sätze über dich …": ["A few sentences about you …", "உங்களைப் பற்றி சில வாக்கியங்கள் …"],
  "Hobbys": ["Hobbies", "பொழுதுபோக்குகள்"],
  "Hobby eintippen, Enter": ["Type a hobby, Enter", "பொழுதுபோக்கை உள்ளிடவும், Enter"],
  "Hobby hinzufügen": ["Add hobby", "பொழுதுபோக்கைச் சேர்"],
  "Beiträge": ["Posts", "பதிவுகள்"],
  "{n} von {max}": ["{n} of {max}", "{max} இல் {n}"],
  "Beitrag löschen": ["Delete post", "பதிவை நீக்கு"],
  "Neuer Beitrag (bis zu {max} Bilder zum Wischen)": ["New post (up to {max} swipeable images)", "புதிய பதிவு (வருடிப் பார்க்க {max} படங்கள் வரை)"],
  "Bilder für den Beitrag auswählen": ["Choose images for the post", "பதிவுக்கான படங்களைத் தேர்ந்தெடு"],
  "Bilder auswählen": ["Choose images", "படங்களைத் தேர்ந்தெடு"],
  "Weitere Bilder": ["More images", "மேலும் படங்கள்"],
  "Bildunterschrift (optional)": ["Caption (optional)", "படத்தலைப்பு (விருப்பத்திற்குரியது)"],
  "Bildunterschrift": ["Caption", "படத்தலைப்பு"],
  "Veröffentliche …": ["Publishing …", "வெளியிடுகிறது …"],
  "Beitrag veröffentlichen": ["Publish post", "பதிவை வெளியிடு"],
  "Höchstens {n} Bilder pro Beitrag.": ["At most {n} images per post.", "ஒரு பதிவுக்கு அதிகபட்சம் {n} படங்கள்."],
  "Höchstens {n} Hobbys.": ["At most {n} hobbies.", "அதிகபட்சம் {n} பொழுதுபோக்குகள்."],
  "Spitzname: 2 bis 24 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["Nickname: 2 to 24 characters, only letters, numbers and simple characters.", "புனைப்பெயர்: 2 முதல் 24 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
  "Hobby: 2 bis 30 Zeichen, nur Buchstaben, Zahlen und einfache Zeichen.": ["Hobby: 2 to 30 characters, only letters, numbers and simple characters.", "பொழுதுபோக்கு: 2 முதல் 30 எழுத்துகள், எழுத்துகள், எண்கள் மற்றும் எளிய குறியீடுகள் மட்டும்."],
  "Das Profilbild konnte nicht hochgeladen werden.": ["The profile picture could not be uploaded.", "சுயவிவரப் படத்தைப் பதிவேற்ற முடியவில்லை."],
  "Der Beitrag konnte nicht veröffentlicht werden.": ["The post could not be published.", "பதிவை வெளியிட முடியவில்லை."],
  "Der Beitrag konnte nicht gelöscht werden.": ["The post could not be deleted.", "பதிவை நீக்க முடியவில்லை."],
  "Dieses Profil ist privat. Mehr als Profilbild und Spitzname siehst du nicht.": ["This profile is private. You only see the profile picture and nickname.", "இந்த சுயவிவரம் தனிப்பட்டது. சுயவிவரப் படமும் புனைப்பெயரும் மட்டுமே தெரியும்."],
  "Noch keine Beiträge.": ["No posts yet.", "இன்னும் பதிவுகள் இல்லை."],
  "Profil bearbeiten": ["Edit profile", "சுயவிவரத்தைத் திருத்து"],
  "{n} Jahre": ["{n} years old", "{n} வயது"],
  "Vorheriges Bild": ["Previous image", "முந்தைய படம்"],
  "Nächstes Bild": ["Next image", "அடுத்த படம்"],
  "Dieses Profil ist privat.": ["This profile is private.", "இந்த சுயவிவரம் தனிப்பட்டது."],
});

register({
  "Profilbild von {name}": ["Profile picture of {name}", "{name} இன் சுயவிவரப் படம்"],
  "Beitrag öffnen": ["Open post", "பதிவைத் திற"],
  "Beitrag von {name}": ["Post by {name}", "{name} இன் பதிவு"],
  "Bild {i} von {n}": ["Image {i} of {n}", "படம் {i} / {n}"],
  "Bild {i}": ["Image {i}", "படம் {i}"],
  "Bild {i} entfernen": ["Remove image {i}", "படம் {i} ஐ அகற்று"],
});

register({
  "Du bist startklar!": ["You're all set!", "நீங்கள் தயார்!"],
  "Anmelden": ["Sign in", "உள்நுழை"],
  "Zum Profil": ["Go to profile", "சுயவிவரத்திற்குச் செல்"],
  "Webseite besuchen": ["Visit website", "இணையதளத்தைப் பார்வையிடு"],
  "Link nicht angekommen? Erneut senden oder andere Adresse": ["Link didn't arrive? Send again or use another address", "இணைப்பு வரவில்லையா? மீண்டும் அனுப்பு அல்லது வேறு முகவரி"],
  "← Zurück zur Startseite": ["← Back to the home page", "← முகப்புப் பக்கத்திற்குத் திரும்பு"],
  "Wir haben dir einen Link an {email} geschickt. Mit einem Klick darauf wirst du angemeldet und dein Profil wird gespeichert.": ["We sent a link to {email}. One click on it signs you in and saves your profile.", "{email} முகவரிக்கு இணைப்பை அனுப்பியுள்ளோம். அதில் ஒரு கிளிக் செய்தால் நீங்கள் உள்நுழைவீர்கள், உங்கள் சுயவிவரம் சேமிக்கப்படும்."],
  "deine E-Mail-Adresse": ["your email address", "உங்கள் மின்னஞ்சல் முகவரி"],
  "Danke, dass du dich weiter geöffnet hast. Deine Antworten sind gespeichert und helfen uns, dich besser kennenzulernen.": ["Thank you for opening up further. Your answers are saved and help us get to know you better.", "மேலும் மனம் திறந்ததற்கு நன்றி. உங்கள் பதில்கள் சேமிக்கப்பட்டுள்ளன, உங்களை நன்றாக அறிய உதவுகின்றன."],
  "Dein Profil ist angelegt. Sobald sich in deinen Hubs genug Leute eintragen, öffnet sich dein Hub und wir melden uns bei dir.": ["Your profile is created. As soon as enough people sign up in your hubs, your hub opens and we will get in touch.", "உங்கள் சுயவிவரம் உருவாக்கப்பட்டது. உங்கள் மையங்களில் போதுமான பேர் பதிவு செய்தவுடன், உங்கள் மையம் திறக்கும், நாங்கள் உங்களைத் தொடர்பு கொள்வோம்."],
  "Dieser Link ist abgelaufen oder wurde schon benutzt. Fordere unten einen neuen an.": ["This link has expired or has already been used. Request a new one below.", "இந்த இணைப்பு காலாவதியாகிவிட்டது அல்லது ஏற்கனவே பயன்படுத்தப்பட்டுவிட்டது. கீழே புதிய இணைப்பைக் கோருங்கள்."],
});
